---
- name: Reset config_path checkout and update to origin/master
  block:
    - name: Set required facts
      ansible.builtin.set_fact:
        config_url: "https://admin:{{ gerrit_admin_api_key }}@{{ gerrit_host }}/a/config"

    - name: "Ensure dir is not available {{ config_path }}"
      ansible.builtin.file:
        path: "{{ config_path }}"
        state: absent

    - name: Clone config repo
      ansible.builtin.command: "git -c http.sslVerify={{ validate_certs }} clone {{ config_url }} {{ config_path }}"
      tags:
        - skip_ansible_lint

    - name: Config repo, ensure config repo cert is trusted
      ansible.builtin.command: git config http.sslverify {{ validate_certs }}
      args:
        chdir: "{{ config_path }}"
      tags:
        - skip_ansible_lint

    - name: Config repo, add git remote
      ansible.builtin.command: "git remote add gerrit {{ config_url }}"
      args:
        chdir: "{{ config_path }}"
      tags:
        - skip_ansible_lint

    - name: Config repo, set user
      ansible.builtin.command: "{{ git_user }}"
      args:
        chdir: "{{ config_path }}"
      loop:
        - git config user.email "admin@{{ fqdn }}"
        - git config user.name "admin"
      loop_control:
        loop_var: git_user
      tags:
        - skip_ansible_lint

    - name: Config repo, reset
      ansible.builtin.command: "{{ git_cmd }}"
      args:
        chdir: "{{ config_path }}"
      loop:
        - git fetch --all
        - git checkout master
        - git reset --hard origin/master --
        - git clean -f -d
      loop_control:
        loop_var: git_cmd
      tags:
        - skip_ansible_lint
