---
- name: Ensure directories ownership
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
  loop:
    - "{{ output_dir }}"
    - "{{ log_directory }}"

- name: "Sync {{ log_directory }} in {{ output_dir }}"
  ansible.builtin.command: "rsync -aq {{ log_directory }}/ {{ output_dir }}/"
