---
- name: "Collect executor log before the scaleup"
  shell: |
    mkdir -p ~/zuul-output/logs/k8s-resources/
    kubectl logs zuul-executor-0 > ~/zuul-output/logs/k8s-resources/zuul-executor-42-zuul-executor-logs.txt

- name: "Scale {{ operation }} on statefulset {{ service.name }}"
  ansible.builtin.include_role:
    name: "roles/update-custom-resource"
  vars:
    cr_spec: "{{ service['scale_' + operation + '_resources'] }}"

- name: "Get replica count for {{ service.name }} to operation {{ operation }}"
  ansible.builtin.command: >
    kubectl get statefulsets {{ service.name }}
    -o jsonpath='{.status.readyReplicas}'
  register: _scale_ready

- name: Check if replica count is correct
  fail:
    msg: "The replica count for service {{ service.name }} is not {{ vars['scale_' + operation + '_replicas'] }}"
  when: _scale_ready.stdout | int != vars['scale_' + operation + '_replicas']
