---
- name: "Collect {{ service.kind }} log before executing the scale command"
  shell: |
    mkdir -p ~/zuul-output/logs/k8s-resources/sf/pod
    kubectl logs {{ service.kind }}/{{ service.name }} > ~/zuul-output/logs/k8s-resources/sf/pod/{{ service.name }}-0-{{ service.name }}-logs0.txt

- name: "Scale  on {{ service.kind }} {{ service.name }}"
  ansible.builtin.command:
    cmd: kubectl scale {{ service.kind }} {{ service.name }} --replicas {{ service.replicas }}

- name: "Get replica count for {{ service.name }}"
  ansible.builtin.command: >
    kubectl get {{ service.kind }} {{ service.name }}
    -o jsonpath='{.status.readyReplicas}'
  register: _scale_ready
  until: _scale_ready.stdout | int == service.replicas
  retries: "{{ service.replicas }}"
  delay: 10
