---
- name: Register commit sha
  ansible.builtin.shell: git log -1 --format="%H"
  args:
    chdir: "{{ repo_path }}"
  register: commitsha

- name: "Wait {{ success_job }} SUCCESS result using zuul-web API"
  ansible.builtin.uri:
    url: "https://{{ zuul_endpoint }}/api/tenant/{{ zuul_tenant }}/builds?job_name={{ success_job }}&newrev={{ commitsha.stdout }}"
    return_content: true
    body_format: json
    validate_certs: "{{ validate_certs }}"
  register: zuul_job_result
  until:
    - "'json' in zuul_job_result"
    - zuul_job_result.json != []
    - "'result' in zuul_job_result.json[0]"
    - zuul_job_result.json[0]["result"] == 'SUCCESS'
  retries: "{{ zuul_api_retries }}"
  delay: "{{ zuul_api_delay }}"
