---
  - name: Deploy Fluent Bit
    ansible.builtin.shell: |
      kubectl -n {{ namespace }} apply -f test-fluentbit.yaml
    args:
      chdir: "{{ loki_dir }}"

  - name: Wait for Fluent Bit pod to be ready
    ansible.builtin.command: kubectl get pod test-fluentbit -n {{ namespace }} -o=jsonpath='{.status.phase}'
    register: fb_ready
    until:
      - fb_ready.stdout != ""
      - '"Running" in fb_ready.stdout'
    retries: 30
    delay: 10