- name: Get pod logs
  vars:
    out_dir: "{{ ansible_user_dir }}/zuul-output/logs/pods-logs"
  shell: |
    mkdir -p {{ out_dir }}
    for ns in $(kubectl get ns -o=custom-columns=NAME:.metadata.name --no-headers); do
      for pod in $(kubectl --namespace ${ns} get pod -o=custom-columns=NAME:.metadata.name --no-headers); do
        for cname in $(kubectl --namespace ${ns} get pod ${pod} -o jsonpath='{.spec.containers[*].name}'); do
          kubectl --namespace ${ns} logs --container=${cname} ${pod} &> {{ out_dir }}/${ns}--${pod}--${cname}.txt
        done
      done
    done
  failed_when: false
