---
config_path: /tmp/config
fqdn: sfop.me

validate_certs: false

gerrit_host: "gerrit.{{ fqdn }}"
zuul_host: "zuul.{{ fqdn }}"
logserver_host: "logserver.{{ fqdn }}"
nodepool_host: "nodepool.{{ fqdn }}"
prometheus_host: "prometheus.{{ fqdn }}"

hosts:
  - "{{ gerrit_host }}"
  - "{{ zuul_host }}"
  - "{{ logserver_host }}"
  - "{{ nodepool_host }}"
  - "{{ prometheus_host }}"

logserver_copy_content_dest: "/tmp/logserver-content"
