---
demo_repos_path: "deploy"
config_path: "{{ zuul.project.src_dir }}/{{ demo_repos_path }}/config"
demo_project_path: "{{ zuul.project.src_dir }}/{{ demo_repos_path }}/demo-project"

cli_global_flags: "--config playbooks/files/sf-operator-cli.yaml"

fqdn: sfop.me

validate_certs: false

zuul_endpoint: "{{ fqdn }}/zuul"
logserver_endpoint: "{{ fqdn }}/logs"
nodepool_endpoint: "{{ fqdn }}/nodepool"
gerrit_host: "gerrit.{{ fqdn }}"

hosts:
  - "{{ fqdn }}"
  - "{{ gerrit_host }}"

logserver_copy_content_dest: "/tmp/logserver-content"

zuul_api_retries: 60
zuul_api_delay: 10
