---
- name: Update SF CR to set Let's Encrypt
  ansible.builtin.include_role:
    name: "update-custom-resource"
  vars:
    check_sf_resource_ready: false
    cr_spec:
      letsEncrypt:
        server: "staging"

# We do not wait for the CR status to be ready because it will never happen as the
# CI deployment Route URL/Host cannot be resolved and thus the http01 challenge will
# fails.
# However here we are able to check that a 'Certificate resources''s challenge is created but
# does not become ready due to http01 challenge failure.
# This partialy verifies the flow with Let's Encrypt.

- name: Ensure nodepool service Certificate not Ready for expected reason
  shell: "kubectl -n sf get challenge -o json | grep {{ fqdn }}"
  register: result
  until:
    - result is success
    - "'DNS problem: NXDOMAIN' in result.stdout or 'Waiting for HTTP-01 challenge propagation' in result.stdout or 'no such host' in result.stdout"
  retries: 6
  delay: 10

- name: Update SF CR to unset Let's Encrypt
  ansible.builtin.include_role:
    name: "update-custom-resource"
  vars:
    cr_spec:
      letsEncrypt:
