---
- name: Start port forwarding to loki-http
  shell: |
    kubectl port-forward service/loki-http 3100 -n sf
  async: 60
  poll: 0

- name: Ensure loki is reachable
  uri:
    url: http://localhost:3100/loki/api/v1/status/buildinfo
    return_content: yes
  register: loki_buildinfo
  delay: 6
  retries: 10
  until: "loki_buildinfo.status == 200 and '2.9.2' in loki_buildinfo.content"

- name: Aggregate logs collected by loki
  ansible.builtin.shell: "~/bin/logcli query '{application=\"zuul\"}' --quiet --limit 5"
  register: zuul_logs
  failed_when: zuul_logs.stdout|length < 1