---
- name: Set random value
  ansible.builtin.set_fact:
    nodepool_diskimage_name: "cloud-{{ lookup('community.general.random_string', special=false, upper=false, length=8) }}-image"

# First attempt a negative test where we expect a failure
- name: Ensure nodepool directory exists
  ansible.builtin.file:
    path: "{{ config_path }}/nodepool"
    state: directory

- name: Set bad Nodepool builder config
  ansible.builtin.blockinfile:
    content: |
      DiskDisk: {}
    path: "{{ config_path }}/nodepool/nodepool-builder.yaml"
    create: true

- name: Commit file in the config repo
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ config_path }}"
  loop:
    - "git add {{ config_path }}/nodepool/nodepool-builder.yaml"
    - "git commit -m 'Add nodepool/nodepool-builder.yaml'"

- ansible.builtin.include_role:
    name: "roles/health-check/config-repo-submit-change"
  vars:
    ensure_config_check_failure: true

# Now proceed with adding a correct tenant file
- name: Reset the config repo
  ansible.builtin.command: "git reset --hard gerrit/master"
  args:
    chdir: "{{ config_path }}"

- name: Ensure nodepool directory exists
  ansible.builtin.file:
    path: "{{ config_path }}/nodepool"
    state: directory

- name: Define nodepool-builder.yaml default content
  ansible.builtin.copy:
    content: |
      diskimages:
        - dib-cmd: /usr/bin/dib-virt-customize /etc/nodepool/virt_images/cloud-centos-7.yaml
          formats:
            - raw
          name: {{ nodepool_diskimage_name }}
          pause: true
          python-path: /usr/bin/python2
          username: zuul-worker
    dest: "{{ config_path }}/nodepool/nodepool-builder.yaml"

- name: Commit file in the config repo
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ config_path }}"
  loop:
    - "git add {{ config_path }}/nodepool/nodepool-builder.yaml"
    - "git commit -m 'Add nodepool/nodepool-builder.yaml'"

- name: Update config repo change
  ansible.builtin.include_role:
    name: "roles/health-check/config-repo-submit-change"

- name: "Check that {{ nodepool_diskimage_name }} label exists in the destination file"
  ansible.builtin.shell: |
    kubectl exec nodepool-builder-0 -- grep "name: {{ nodepool_diskimage_name }}" /etc/nodepool/nodepool.yaml
