- name: Install busybox from quay.io to avoid docker.io rate limit
  delegate_to: "{{ os_host }}"
  ansible.builtin.command: "{{ busybox_setup }}"
  loop:
    - podman pull quay.io/software-factory/busybox
    - podman image tag quay.io/software-factory/busybox:latest docker.io/library/busybox:1.36.0
  become: yes
  loop_control:
    loop_var: busybox_setup

- name: Install the operator via the OLM bundle
  delegate_to: "{{ os_host }}"
  ansible.builtin.command: >
    bin/operator-sdk
    run
    bundle
    --timeout 4m0s
    --skip-tls
    --skip-tls-verify
    {{ ci_bundle_img }}
    --namespace operators
    --security-context-config restricted
  register: run_bundle
  retries: 3
  delay: 10
  until: run_bundle is success
  args:
    chdir: "{{ zuul.project.src_dir }}"
