- job:
    name: sf-operator-functional-allinone
    run: playbooks/test.yaml
    post-run: playbooks/post.yaml
    nodeset:
      nodes:
        name: controller
        label: cloud-fedora-36
    required-projects:
      - name: software-factory/sf-infra
    roles:
      - zuul: software-factory/sf-infra
    vars:
      logclassify_logserver_dir: ./
      logclassify_debug: false
      logclassify_report: true

- project:
    check:
      jobs:
        - sf-operator-functional-allinone
    gate:
      jobs:
        - sf-operator-functional-allinone
