- job:
    name: sf-operator-functional-minimal
    run: playbooks/test.yaml
    nodeset:
      nodes:
        name: controller
        label: cloud-fedora-36

- project:
    check:
      jobs:
        - sf-operator-functional-minimal
    gate:
      jobs:
        - noop
