- job:
    name: sf-operator-functional-allinone
    run: playbooks/test.yaml
    post-run: playbooks/post.yaml
    nodeset:
      nodes:
        name: controller
        label: cloud-fedora-36

- project:
    check:
      jobs:
        - sf-operator-functional-allinone
    gate:
      jobs:
        - noop
