ansible_microshift_role_path: ~/src/github.com/openstack-k8s-operators/ansible-microshift-role
microshift:
  host: microshift.dev
  user: cloud-user
fqdn: sftests.com
nodepool:
  clouds_file: /etc/sf-operator/nodepool/clouds.yaml
  kube_file: /etc/sf-operator/nodepool/kubeconfig.yaml
