---
- name: Ensure prometheus instance exists
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Prometheus
    name: prometheus
    namespace: sf

- name: Ensure instance is reachable via route
  ansible.builtin.uri:
    url: https://{{ prometheus_host }}
    status_code: [302, 200]
    validate_certs: "{{ validate_certs }}"

- name: Fetch defined Prometheus targets
  ansible.builtin.shell: curl -k https://{{ prometheus_host }}/api/v1/targets | jq '.data.activeTargets[] | select(.labels.container == "{{ item }}") | .health'
  register: target_health
  failed_when: "\"up\" not in target_health.stdout"
  loop:
    - "zuul-web"
    - "zuul-executor"
    - "zuul-scheduler"
    - "logserver-nodeexporter"

- name: Fetch defined alerts for logserver
  ansible.builtin.shell: curl -k https://{{ prometheus_host }}/api/v1/rules | jq '.data.groups[] | select(.name == "disk_default.rules") | .rules[] | select(.name == "{{ item }}") | .health'
  register: logserver_alert
  failed_when: "\"ok\" not in logserver_alert.stdout"
  loop:
    - "OutOfDiskNow"
    - "OutOfDiskInThreeDays"

- name: Fetch a basic Zuul metric exporter by statsd
  ansible.builtin.shell: curl -k https://{{ prometheus_host }}/api/v1/query?query=zuul_executors_online | jq '.data.result[0].value[1]'
  register: zeo

  # config-update-nodepool-builder should at least trigger one tick for readiness.
- name: Fetch a basic Nodepool metric exported by statsd
  ansible.builtin.shell: curl -k https://{{ prometheus_host }}/api/v1/query?query=nodepool_launch_ready | jq '.data.result[0].value[1]'
  register: nlr

# Use a dictionary to trick Ansible into casting metrics to int/float
- set_fact:
    metric_yaml:
      zeo: "{{ zeo.stdout_lines[-1][1:-1] | int }}"
      nlr: "{{ nlr.stdout_lines[-1][1:-1] | float }}"

- set_fact:
    metric_dict: "{{ metric_yaml | from_yaml }}"

- fail:
    msg: Unexpected value for zuul_executors_online
  when: metric_dict.zeo | int < 1

- fail:
    msg: Unexpected value for nodepool_launch_ready
  when: metric_dict.nlr | float < 1