- hosts: microshift
  tasks:
    - name: Create namespaces
      ansible.builtin.shell: kubectl get namespace {{ item }} || kubectl create namespace {{ item }}
      loop:
        - operators
        - sf
        - nodepool
        - ext-ze
    - name: Set service accounts privileges
      ansible.builtin.command: oc adm policy add-scc-to-user privileged system:serviceaccount:{{ item.namespace }}:{{ item.serviceaccount }}
      loop:
        - namespace: operators
          serviceaccount: default
        - namespace: sf
          serviceaccount: default
        - namespace: ext-ze
          serviceaccount: default
        - namespace: operators
          serviceaccount: prometheus-operator
    - name: Set default kubectl context to sf namespace
      ansible.builtin.command: kubectl config set-context microshift --namespace=sf
    # TODO we do this so that this playbook doesn't rely on a local copy of the repo. There may be a better way to do that.
    - name: Ensure certmanager operator is installed
      block:
        - name: Apply certmanager subscription
          ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/softwarefactory-project/sf-operator/master/olm-deps/cert-manager.yaml
        - name: Wait for pod to be ready
          ansible.builtin.command: >
            kubectl wait --for=condition=Ready --timeout 5s pods
            -l app.kubernetes.io/instance=cert-manager -n operators
          register: ready_cm
          until:
            - '"condition met" in ready_cm.stdout'
            - ready_cm.rc == 0
          retries: 60
          delay: 5
    - name: Ensure prometheus operator is installed
      block:
        - name: Apply prometheus-operator subscription
          ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/softwarefactory-project/sf-operator/master/olm-deps/prometheus/prometheus-subscription.yaml
        - name: Wait for pod to be ready
          ansible.builtin.command: >
            kubectl wait --for=condition=Ready --timeout 5s pods
            -l app.kubernetes.io/name=prometheus-operator -n operators
          register: ready_po
          until:
            - '"condition met" in ready_po.stdout'
            - ready_po.rc == 0
          retries: 60
          delay: 5
