---
- name: Set up nodepool namespace
  ansible.builtin.shell: >
    go run ./main.go {{ cli_global_flags }} nodepool create openshiftpods-namespace
  args:
    chdir: "{{ zuul.project.src_dir | default(src_dir) }}"