- name: Install dependencies
  block:
    - name: Install packages
      package:
        name:
          - golang
          - make
          # for testing
          - jq
          - python3-pip
      become: true

    - name: Install git-review
      pip:
        name: git-review
  when: install_requirements | bool == true

- name: Check cluster access
  command: kubectl cluster-info

- name: Install cert-manager operator
  command: make install-cert-manager
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Install the CRDS
  command: make install
  args:
    chdir: "{{ zuul.project.src_dir }}"
