- name: Install packages
  package:
    name:
      - golang
      - make
  become: true

- name: Check cluster access
  command: kubectl cluster-info

- name: Install cert-manager operator
  command: make install-cert-manager
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Install sf-operator CRDs
  command: make install
  args:
    chdir: "{{ zuul.project.src_dir }}"
