- name: Install packages
  package:
    name:
      - golang
      - make
  become: true
  when: install_requirements | bool == true

- name: Check cluster access
  command: oc cluster-info

- name: Install cert-manager operator
  command: make install-cert-manager
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Install the CRDS
  command: make install
  args:
    chdir: "{{ zuul.project.src_dir }}"
