---
- name: Add custom self signed cert
  ansible.builtin.shell: >
    ./tools/sfconfig
    create-service-ssl-secret
    --sf-service-ca {{ ssl_path }}/localCA.pem
    --sf-service-key {{ ssl_path }}/ssl.key
    --sf-service-cert {{ ssl_path }}/ssl.crt
    --sf-service-name {{ service_name_custom_ssl }}
  args:
    chdir: "{{ zuul.project.src_dir | default(src_dir) }}"
