---
- name: Get new certificate content
  ansible.builtin.shell: cat {{ ssl_path }}/ssl.crt
  register: _ssl_content

- name: Verify that the SSL is in the secret
  ansible.builtin.shell: >
    kubectl get secret {{ service_name_custom_ssl }}-ssl-cert -o json |
    jq -r ".data.crt" | base64 -d
  register: _new_cert_secret

- name: Ensure that the cert and secret cert are same
  ansible.builtin.assert:
    that:
      - _ssl_content.stdout == _new_cert_secret.stdout

- name: Make a query to validate that the route exposes the expected certificate
  ansible.builtin.shell: >
    openssl s_client
    -showcerts
    -servername {{ common_name }}
    -connect {{ common_name }}:443
  register: _new_cert_subj
  until: _ssl_content.stdout in _new_cert_subj.stdout
  retries: 10
  delay: 3
