---
- name: Gen CA privkey
  community.crypto.openssl_privatekey:
    path: "{{ ssl_path }}/localCA.key"

- name: Generate CA CSR
  community.crypto.openssl_csr:
    path: "{{ ssl_path }}/localCA.csr"
    privatekey_path: "{{ ssl_path }}/localCA.key"
    country_name: "{{ country_name }}"
    organization_name: "{{ org_name }}"
    common_name: "{{ ca_common_name }}"
    state_or_province_name: "{{ random_state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    organizational_unit_name: "{{ organizational_unit_name }}"
    basic_constraints:
      - CA:TRUE
    key_usage:
      - cRLSign
      - keyCertSign
      - keyEncipherment
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
      - serverAuth

- name: Generate selfsigned CA certificate
  openssl_certificate:
    path: "{{ ssl_path }}/localCA.pem"
    csr_path: "{{ ssl_path }}/localCA.csr"
    privatekey_path: "{{ ssl_path }}/localCA.key"
    provider: selfsigned
    selfsigned_digest: sha256
