---
- name: Check that ca-bundle contains the localCA certificate
  ansible.builtin.shell: |
    kubectl exec {{ item }} -- bash -c "grep '{{ ca_common_name }}' /etc/pki/tls/certs/ca-bundle.crt"
  register: witness
  until: witness is success
  loop:
    - sts/zuul-scheduler
    - sts/zuul-merger
    - sts/zuul-executor
    - sts/nodepool-builder
    - deploy/nodepool-launcher
  delay: 5
  retries: 6
