---
- name: Retrieve localCA.pem content
  ansible.builtin.slurp:
    src: "{{ ssl_path }}/localCA.pem"
  register: localca

- name: Install corporate-ca-certs ConfigMap
  kubernetes.core.k8s:
    state: present
    name: corporate-ca-certs
    namespace: sf
    definition: |
      kind: ConfigMap
      apiVersion: v1
      type: Opaque
      data:
        local-ca.crt: "{{ localca['content'] | b64decode }}"
