---
- name: Create temporary directory for the custom CA and Route certificate
  ansible.builtin.tempfile:
    state: directory
    suffix: ssl
  register: tempdir

- set_fact:
    ssl_path: "{{ tempdir.path }}"
    random_state_or_province_name: "{{ lookup('community.general.random_string', special=false, length=8) }}"

- name: Generate CA certificate
  ansible.builtin.include_tasks: ca.yaml

- name: Validate Corporate CA certificates installation
  block:
    - name: Add the coporate ca certs Config Map
      ansible.builtin.include_tasks: install_corporate_ca_certs_cm.yaml

    - ansible.builtin.include_role:
        name: "health-check/check-sf-resource-ready"

    - name: Check that generated CA trust chain contains the localCA cert
      ansible.builtin.include_tasks: check_ca_trust_chain.yaml

- name: Validate Route custom TLS setting
  block:
    - name: Generate Client certificate
      ansible.builtin.include_tasks: client-cert.yaml

    - name: Add SSL cert for route as secret
      ansible.builtin.include_tasks: install_sf_ssl_cert.yaml

    - ansible.builtin.include_role:
        name: "health-check/check-sf-resource-ready"

    - name: Check SSL for the route
      ansible.builtin.include_tasks: check_route.yaml
