---
- name: Install the cert-manager operator
  ansible.builtin.command: make install-cert-manager
  args:
    chdir: "{{ zuul.project.src_dir }}"

# Mitigate the issue
# 'failed calling webhook "mutate.webhooks.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook-service.operators.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook-service"'
- name: Ensure cert-manager webhooks deployment really ready
  command: kubectl -n operators get deployment cert-manager-webhook -o yaml
  register: cert_manager_dep
  until: "'readyReplicas: 1' in cert_manager_dep.stdout"
  retries: 10
  delay: 2

- name: Run the operator in devel mode
  ansible.builtin.command: "{{ item }}"
  loop:
    - make install
    - go run ./main.go --namespace sf --cr config/samples/sf_v1_softwarefactory.yaml --oneshot
  args:
    chdir: "{{ zuul.project.src_dir }}"
