---
- name: Run the sfconfig command to get started
  ansible.builtin.command: go run ./cli/sfconfig
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Run the operator in devel mode (in background)
  async: 3600
  poll: 0
  ansible.builtin.shell: |
    go run ./main.go --namespace sf > ~/zuul-output/logs/sf-operator.log 2>&1
  args:
    chdir: "{{ zuul.project.src_dir }}"
