- hosts: all
  tasks:
    - name: Setup dstat
      block:
        - name: Install dstat package
          ansible.builtin.package:
            name: dstat
            state: present
          become: true

        - ansible.builtin.include_role:
            name: "{{ item }}"
          loop:
            - ensure-dstat-graph
            - run-dstat
      when: ansible_distribution == "CentOS"
