apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-updater

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-updater-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - zuul-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-updater
subjects:
  - kind: ServiceAccount
    name: config-updater
roleRef:
  kind: Role
  name: config-updater-role
  apiGroup: rbac.authorization.k8s.io
