apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-updater

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-updater-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
      - persistentvolumeclaims
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-updater
subjects:
  - kind: ServiceAccount
    name: config-updater
roleRef:
  kind: Role
  name: config-updater-role
  apiGroup: rbac.authorization.k8s.io
