- hosts: localhost
  tasks:
    - name: Install required packages
      ansible.builtin.include_role:
        name: "roles/setup-env"

    - name: Populate /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ microshift_ip }} {{ microshift_fqdn }}
          {{ microshift_ip }} zuul.{{ sf_fqdn }}
          {{ microshift_ip }} gerrit.{{ sf_fqdn }}
          {{ microshift_ip }} logserver.{{ sf_fqdn }}
          {{ microshift_ip }} nodepool.{{ sf_fqdn }}
      become: yes
