- hosts: localhost
  tasks:
    - name: clone microshift role
      ansible.builtin.git:
        repo: https://github.com/openstack-k8s-operators/ansible-microshift-role
        dest: "{{ microshift_role_path }}"
        update: yes

    - name: Install microshift repos
      ansible.builtin.include_role:
        name: "{{ microshift_role_path }}"
        tasks_from: repo
      when: ansible_distribution == "CentOS"

    - name: Install rpms
      block:
        - name: Install epel
          ansible.builtin.package:
            name: epel-release
          when: ansible_distribution == "CentOS"

        - name: Install packages
          ansible.builtin.package:
            name:
              - ansible
              - ansible-core
              - git-review
              - golang
              - jq

        - name: Install openshift-client
          ansible.builtin.package:
            name: openshift-clients
            enablerepo: microshift-deps-rpms
          when: ansible_distribution == "CentOS"

        - name: Install kubernetes-client
          ansible.builtin.package:
            name: kubernetes-client
          when: ansible_distribution == "Fedora"
      become: yes

    - name: Populate /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {{ microshift_ip }} {{ microshift_fqdn }}
          {{ microshift_ip }} zuul.{{ sf_fqdn }}
          {{ microshift_ip }} gerrit.{{ sf_fqdn }}
          {{ microshift_ip }} logserver.{{ sf_fqdn }}
      become: yes
