# permissions for end users to edit configcheckjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configcheckjob-editor-role
rules:
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - configcheckjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - configcheckjobs/status
  verbs:
  - get
