---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - deployments
  - jobs
  - persistentvolumeclaims
  - pods
  - pods/exec
  - rolebindings
  - roles
  - routes
  - routes/custom-host
  - secrets
  - serviceaccounts
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - configmaps/status
  - deployments/status
  - jobs/status
  - persistentvolumeclaims/status
  - pods/status
  - roles/status
  - routes/status
  - secrets/status
  - serviceaccounts/status
  - services/status
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - cert-manager.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - configcheckjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - configcheckjobs/finalizers
  verbs:
  - update
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - configcheckjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - logservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - logservers/finalizers
  verbs:
  - update
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - logservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories/finalizers
  verbs:
  - update
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories/status
  verbs:
  - get
  - patch
  - update
