---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories/finalizers
  verbs:
  - update
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories/status
  verbs:
  - get
  - patch
  - update
