# permissions for end users to edit softwarefactories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: softwarefactory-editor-role
rules:
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories/status
  verbs:
  - get
