# permissions for end users to view softwarefactories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: softwarefactory-viewer-role
rules:
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sf.softwarefactory-project.io
  resources:
  - softwarefactories/status
  verbs:
  - get
