---
- name: Create a resources file
  ansible.builtin.copy:
    content: |
      resources:
        projects:
          {{ repository_name }}:
            tenant: internal
            description: The best cloud platform engine
            source-repositories:
              - {{ repository_name }}:
                  connection: gerrit
                  zuul/config-project: True
        repos:
          {{ repository_name }}:
            description: The config project of ichiban-cloud
            acl: config-acl
    dest: "{{ config_path }}/{{ config_file_path }}"

- name: Commit file in the config repo
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ config_path }}"
  loop:
    - "git add {{ config_file_path }}"
    - "git commit -m 'Add {{ config_file_path }}'"
