- name: Creating a file in Zuul Excutor Statefulset
  command: |
    {{ oc_container_runner }} zuul-executor-0 -- touch /tmp/{{ logserver_file }}

- name: Sync file between Zuul Executor and Logserver
  command: |
    {{ oc_container_runner }} zuul-executor-0 -- rsync -v -Par -e 'ssh -p {{ sshd_port }} -i /var/lib/zuul-ssh/priv -o "StrictHostKeyChecking=no"' /tmp/{{ logserver_file }} data@logserver-sshd:/home/data/rsync/

- name: Attempt to get file from Logserver WEB via the ingress
  ansible.builtin.uri:
    url: "https://{{ logserver_host }}/logs/{{ logserver_file }}"
    method: GET
    status_code: 200
    validate_certs: "{{ validate_certs }}"

- name: Delete Logserver file
  command: |
    {{ oc_container_runner }} logserver-0 -c logserver-sshd -- rm /home/data/rsync/{{ logserver_file }}
