- name: Create a zuul-client configuration file
  ansible.builtin.shell: >
    go run ./main.go --config {{ ansible_user_dir }}/sfcontext.yaml zuul create client-config --insecure
  register: zc_config
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Save zuul-client configuration to file
  ansible.builtin.copy:
    content: "{{ zc_config.stdout }}"
    dest: "{{ ansible_user_dir }}/zuul-client.conf"

- name: Create a autohold request with zuul-client and the generated config
  ansible.builtin.command: |
    zuul-client -c {{ ansible_user_dir }}/zuul-client.conf --use-config internal autohold --project config --job config-update --reason CI_TEST
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Ensure autohold was set properly
  ansible.builtin.command: |
    zuul-client -c {{ ansible_user_dir }}/zuul-client.conf --use-config internal autohold-list
  register: _ah_list
  failed_when: "\"CI_TEST\" not in _ah_list.stdout"

- name: Remove autohold
  ansible.builtin.shell: >
    echo "{{ _ah_list.stdout }}" |
    grep -oE "0000[0-9]+" |
    xargs zuul-client -c {{ ansible_user_dir }}/zuul-client.conf --use-config internal autohold-delete
