---
- name: Set operator_version_expression fact
  ansible.builtin.set_fact:
    operator_version_expression: "sf-operator.{{ upgrade_version }}"

- name: Wait for sf-operator version
  ansible.builtin.command: >
    kubectl -n operators get deployment.apps/sf-operator-controller-manager
    -o jsonpath="{.metadata.labels['olm\.owner']}"
  register: operator_owner
  until:
    - operator_owner.stdout == operator_version_expression
  retries: "{{ retries }}"
  delay: "{{ delay }}"

- name: Wait for sf-operator deployment ready
  ansible.builtin.command: >
    kubectl -n operators get deployment.apps/sf-operator-controller-manager
    -o jsonpath="{.status.readyReplicas}"
  register: operator_ready_replicas
  until:
    - operator_ready_replicas.stdout == "1"
  retries: "{{ retries }}"
  delay: "{{ delay }}"
