apiVersion: v1
kind: ServiceAccount
metadata:
  name: sf-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sf-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - sf-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - operator.softwarefactory-project.io
  resources:
  - '*'
  verbs:
  - '*'

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sf-operator
subjects:
- kind: ServiceAccount
  name: sf-operator
roleRef:
  kind: Role
  name: sf-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sf-operator-zuul
subjects:
- kind: ServiceAccount
  name: sf-operator
roleRef:
  kind: Role
  name: zuul-operator
  apiGroup: rbac.authorization.k8s.io
