---
- name: Run sf-operator restore
  ansible.builtin.command: |
    go run main.go SF restore --backup_dir {{ backup_dir }} {{ cli_global_flags }}
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Get secret test in namespace sf after restore
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ restore_secret_name }}"
    namespace: "{{ namespace }}"
  register: secret_result

- name: Get base64 for restore data value
  ansible.builtin.set_fact:
    secret_restore: "{{ secret_result.resources[0] }}"

- name: Assert that secrets b64 after restore are same
  ansible.builtin.assert:
    that:
      - secret_before.data == secret_restore.data

- name: Get available tables
  kubernetes.core.k8s_exec:
    namespace: "{{ namespace }}"
    pod: mariadb-0
    command: >
      mysql -h 0 -u root
      -p{{ db_root_pass }}
      -e "USE zuul; SHOW TABLES;"
  register: _show_tables

- name: Ensure that there is no Zuul DB
  ansible.builtin.assert:
    that:
      - "'zuul_restore_test' not in _show_tables.stdout"

- name: Export new Zuul keys in the pod after restore
  kubernetes.core.k8s_exec:
    namespace: "{{ namespace }}"
    pod: zuul-scheduler-0
    command: >
      zuul-admin export-keys /tmp/restored-key

- name: Check if the demo-tenant-config is in new exported file
  kubernetes.core.k8s_exec:
    namespace: "{{ namespace }}"
    pod: zuul-scheduler-0
    command: >
      grep -c demo-tenant-config /tmp/restored-key
  register: _count_project_restore_key

- name: Assert that the demo-tenant-config has been removed
  ansible.builtin.assert:
    that:
      - _count_project_restore_key.stdout | int == 1
