---
- name: Enable log forwarding
  ansible.builtin.include_role:
    name: "update-custom-resource"
  vars:
    cr_spec:
      FluentBitLogForwarding:
        forwardInputHost: fluent-bit-forward-input
        forwardInputPort: 24224