---
- name: Enable log forwarding
  ansible.builtin.include_role:
    name: "update-custom-resource"
  vars:
    cr_spec:
      FluentBitLogForwarding:
        httpInputHost: fluent-bit-http-input
        httpInputPort: 5140