---
- name: "Ensure removal of {{ output_dir }}"
  ansible.builtin.file:
    path: "{{ output_dir }}"
    state: absent

- name: "Ensure {{ output_dir }}"
  ansible.builtin.file:
    path: "{{ output_dir }}"
    state: directory

- name: Get nodes information
  ansible.builtin.shell: |
    kubectl describe nodes > {{ output_dir }}/nodes.txt

- name: Describe CRDs
  ansible.builtin.shell: |
    mkdir -p {{ output_dir }}/CRDs
    for item in $(kubectl get crd -o name); do
      mkdir -p {{ output_dir }}/CRDs/$(dirname $item)
      oc describe $item > {{ output_dir }}/CRDs/${item}.txt
    done

- name: Describe resources
  ansible.builtin.shell: |
    for item in $(kubectl get {{ item }} -o name); do
      mkdir -p {{ output_dir }}/$(dirname $item)
      kubectl describe $item > {{ output_dir }}/${item}.txt
    done
  ignore_errors: true
  loop:
    - pv
  tags:
    skip_ansible_lint
