apiVersion: sf.softwarefactory-project.io/v1
kind: ConfigCheckJob
metadata:
  name: configcheckjob-sample
spec:
  ttl: 600
  zuulTenantConfig: |
    ---
    - tenant:
        name: tenant_one
        source: {}