apiVersion: sf.softwarefactory-project.io/v1
kind: SoftwareFactory
metadata:
  name: my-sf
spec:
  fqdn: "sftests.com"
  etherpad:
    enabled: true
  lodgeit:
    enabled: true
  gerrit:
    enabled: true
    sshd_max_connections_per_user: "64"
  opensearch:
    enabled: true
  opensearchdashboards:
    enabled: true
  zuul:
    enabled: true
    gerritconns: []
  murmur:
    enabled: true
    maxusers: 42
    channels:
      - name: Dev
        description: Developers lounge
      - name: Meeting
        description: Meeting room
      - name: Meeting-Alt
        description: Second meeting room
