---
- name: Get current volume size
  ansible.builtin.shell: >
    kubectl get pvc logserver
    --output custom-columns=CAPACITY:.status.capacity.storage
    --no-headers | sed 's/[^0-9]\+//'
  register: logserver_capacity

- name: Increase volume size
  ansible.builtin.set_fact:
    volume_size: "{{ logserver_capacity.stdout | int + 2 }}"

- name: Expand logserver volume
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    definition:
      # apiVersion: sf.softwarefactory-project.io/v1
      kind: SoftwareFactory
      namespace: sf
      metadata:
        name: my-sf
        namespace: sf
      spec:
        logserver:
          storage:
            size: "{{ volume_size }}Gi"

- name: Wait until resize is effective
  shell: |
    kubectl describe pvc logserver
  register: pvc_events
  until: "'MountVolume.NodeExpandVolume succeeded for volume' in pvc_events.stdout"
  delay: 10
  retries: 20

- ansible.builtin.include_role:
    name: "roles/health-check/check-sf-resource-ready"

- name: Ensure volume expansion to {{ volume_size }}Gi
  command: |
    kubectl get pvc logserver --output custom-columns=CAPACITY:.status.capacity.storage --no-headers
  register: logserver_capacity
  failed_when: logserver_capacity.stdout != '{{ volume_size }}Gi'
