- name: Clone microshift role
  ansible.builtin.git:
    repo: https://github.com/openstack-k8s-operators/ansible-microshift-role
    dest: "{{ microshift_role_path }}"
    update: yes
    version: "{{ microshift_role_version }}"
