---
- name: Install dependencies
  become: true
  when: install_requirements
  block:
    - name: Upgrade all packages
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Get microshift bits for CentOS
      block:
        - ansible.builtin.include_tasks:
            file: clone-microshift-role.yaml

        - name: Install microshift repos
          ansible.builtin.include_role:
            name: "{{ microshift_role_path }}"
            tasks_from: repo
      when:
        - ansible_distribution == "CentOS"
        - os_host != 'controller'

    - name: Check if kubeconfig exists
      stat:
        path: ~/.kube/config
      register: _kubeconfig
      become: false

    - name: Ensure kubeconfig has fqdn
      ansible.builtin.command: sed 's/localhost/{{ microshift_fqdn }}/' -i ~/.kube/config
      when: _kubeconfig.stat.exists
      become: false

    - name: Install epel to get git-review
      ansible.builtin.package:
        name: epel-release
      when: ansible_distribution == "CentOS"

    - name: Install packages
      ansible.builtin.package:
        name:
          - git-review
          - golang
          - jq
          - make
          - podman
          - buildah
          - skopeo
          - openssl
          - python3-cryptography

    - name: Install openshift-client
      ansible.builtin.package:
        name:
          - openshift-clients
        enablerepo: microshift-deps-rpms
      when: ansible_distribution == "CentOS"

    - name: Install kubernetes-client and python3
      ansible.builtin.package:
        name:
          - kubernetes-client
      when: ansible_distribution == "Fedora"

    - name: Install python3-pip
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-setuptools

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - git-review
          - kubernetes
          - oauthlib>=3.2.2
          - websocket-client
