- name: Install dependencies
  become: true
  when: install_requirements | bool
  block:
    - name: Install packages
      package:
        name:
          - golang
          - make
          - podman
          # for testing
          - jq
          - python3-pip

    - name: Install pip packages
      pip:
        name:
          - git-review
          - kubernetes
          - oauthlib>=3.2.2
          - websocket-client==1.5.1
