---
- name: Install required packages
  ansible.builtin.include_role:
    name: "roles/setup-env"

- name: Run deploy microshift playbook
  ansible.builtin.include_tasks: deploy-microshift.yaml

- name: Run post install playbook
  ansible.builtin.include_tasks: post-install.yaml
