---
- name: Run sf-operator backup
  ansible.builtin.command: |
    go run main.go SF backup --backup_dir {{ backup_dir }} {{ cli_global_flags }}
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Ensure directories are not empty
  ansible.builtin.include_tasks:
    file: check_dir.yaml
  loop:
    - secrets
    - mariadb
    - zuul
  loop_control:
    loop_var: backup_subdir

- name: Compare secrets
  ansible.builtin.include_tasks:
    file: secrets.yaml
  loop:
    - name: zuul-keystore-password
      data_key: zuul-keystore-password
  loop_control:
    loop_var: secret_name

- name: Check SQL backup
  ansible.builtin.include_tasks:
    file: sql.yaml

- name: Check Zuul backup
  ansible.builtin.include_tasks:
    file: zuul.yaml
