---
- name: "Get password from the secret - {{ secret_name.name }}"
  ansible.builtin.shell: |
    kubectl -n {{ namespace }} get secret {{ secret_name.name }} -o go-template --template {% raw %}'{{.data}}' {% endraw %} | cut -f2 -d':'
  register: _b64_pass

- name: "Get password from a backup file - {{ secret_name.name }}"
  ansible.builtin.shell: |
    grep '{{ secret_name.data_key }}:' {{ backup_dir }}/secrets/{{ secret_name.name }}.yaml  | awk '{print $2}'
  register: _file_pass

- name: Ensure that password from backup and in Kubernetes are same
  ansible.builtin.assert:
    that:
      - _b64_pass.stdout | b64decode == _file_pass.stdout
