- name: Create ssh key
  command: "ssh-keygen -f /opt/ansible/ssh-{{ key_name }} -m PEM -t rsa -N '' -C '{{ key_comment }}'"
  args:
    creates: "/opt/ansible/ssh-{{ key_name }}"

- name: Create ssh secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        labels: "{{ k8s_labels }}"
        name: "{{ secret_name }}"
        namespace: "{{ namespace }}"
      type: Opaque
      data:
        id_rsa: "{{ lookup('file', '/opt/ansible/ssh-' + key_name) | b64encode }}"
        id_rsa.pub: "{{ lookup('file', '/opt/ansible/ssh-' + key_name + '.pub') | b64encode }}"
