apiVersion: sf.softwarefactory-project.io/v1
kind: SoftwareFactory
metadata:
  name: my-sf
spec:
  fqdn: "sfop.me"
  config-location:
    base-url: "http://gerrit-httpd/"
    name: config
    zuul-connection-name: gerrit
    k8s-api-url: "https://microshift.dev:6443"
    logserver-host: microshift.dev
  zuul:
    gerritconns:
      - name: gerrit
        username: zuul
        hostname: microshift.dev
        puburl: "https://gerrit.sfop.me"
        verifyssl: false
    executor:
      enabled: false
  logserver:
    loopDelay: 3600
    retentionDays: 30
    storage:
      size: 2Gi
  # NOTE: use "crc-csi-hostpath-provisioner" in CRC deployment
  storageClassName: "topolvm-provisioner"
