- set_fact:
    namespace_opt: "-n {{ namespace }}"
    dest_dir: "{{ output_dir }}/{{ namespace }}"

- name: "Ensure removal of {{ dest_dir }}"
  file:
    path: "{{ dest_dir }}"
    state: absent

- name: "Ensure {{ dest_dir }}"
  file:
    path: "{{ dest_dir }}"
    state: directory

- name: Get all resources
  shell: |
    kubectl {{ namespace_opt }} get all > {{ dest_dir }}/resources-all.txt

- name: Get events
  shell: |
    kubectl {{ namespace_opt }} get events > {{ dest_dir }}/events.txt

- name: Describe namespace resources
  shell: |
    for item in $(kubectl {{ namespace_opt }} get {{ item }} -o name); do
      mkdir -p {{ dest_dir }}/$(dirname $item)
      kubectl {{ namespace_opt }} describe $item > {{ dest_dir }}/${item}.txt
    done
  ignore_errors: true
  loop:
    - pods
    - deployments
    - statefulsets
    - services
    - secrets
    - configmaps
    - jobs
    - pvc
    - cvs
    - sub
    - catalogsources

- name: Collect namespace pods logs
  shell: |
    mkdir -p {{ dest_dir }}/pod
    for pod in $(kubectl {{ namespace_opt }} get pods -o name); do
      for container in $(kubectl {{ namespace_opt }} get $pod -o jsonpath='{.spec.containers[*].name}'); do
        kubectl {{ namespace_opt }} logs $pod -c $container > {{ dest_dir }}/${pod}-${container}-logs.txt
      done
    done
