---
- name: Get current volume size
  ansible.builtin.shell: >
    kubectl get pvc logserver-logserver-0
    --output custom-columns=CAPACITY:.status.capacity.storage
    --no-headers | sed 's/[^0-9]\+//'
  register: logserver_capacity

- name: Increase volume size
  ansible.builtin.set_fact:
    volume_size: "{{ logserver_capacity.stdout | int + 2 }}"

- name: Expand logserver volume
  ansible.builtin.include_role:
    name: "update-custom-resource"
  vars:
    cr_spec:
      logserver:
        storage:
          size: "{{ volume_size }}Gi"

- name: Ensure volume expansion to {{ volume_size }}Gi
  ansible.builtin.shell: >
    kubectl get pvc logserver-logserver-0
    --output custom-columns=CAPACITY:.status.capacity.storage
    --no-headers | sed 's/[^0-9]\+//'
  register: logserver_capacity
  failed_when: logserver_capacity.stdout | int != volume_size | int
