- name: Reset  config_path checkout and update to origin/master
  block:
    - set_fact:
        config_url: "https://admin:{{ gerrit_admin_api_key }}@{{ gerrit_host}}/a/config"

    - name: "Ensure {{ config_path }} absent"
      file:
        path: "{{ config_path }}"
        state: absent

    - name: Clone config repo
      command: "git -c http.sslVerify={{ validate_certs }} clone {{ config_url }} {{ config_path }}"

    - name: config repo, ensure config repo cert is trusted
      command: git config http.sslverify {{ validate_certs }}
      args:
        chdir: "{{ config_path }}"

    - name: config repo, add git remote
      command: "git remote add gerrit {{ config_url }}"
      args:
        chdir: "{{ config_path }}"

    - name: config repo, set user
      shell: "{{ git_user }}"
      args:
        chdir: "{{ config_path }}"
      loop:
        - git config user.email "admin@sftests.com"
        - git config user.name "admin"
      loop_control:
        loop_var: git_user

    - name: config repo, reset
      command: "{{ git_cmd }}"
      args:
        chdir: "{{ config_path }}"
      loop:
        - git fetch --all
        - git checkout master
        - git reset --hard origin/master --
        - git clean -f -d
      loop_control:
        loop_var: git_cmd
