---
- name: Iterate on preparation roles
  ansible.builtin.include_role:
    name: "{{ role.name }}"
  when: role.when | default(true)
  loop:
    - name: setup-variables
    - name: run-operator-standalone
      when: "{{ mode == 'standalone' }}"
    - name: setup-nodepool-ns
    - name: run-operator-standalone
      when: "{{ mode == 'standalone' }}"
    - name: utils/manage-hosts
    - name: utils/get-gerrit-admin-user-api-key
    - name: utils/config-repo-reset
    - name: utils/setup-log-forwarding-stack
  loop_control:
    loop_var: role

- name: Iterate on tests
  ansible.builtin.include_role:
    name: "health-check/{{ role.name }}"
  when: role.when | default(true)
  loop:
    - name: check-service-uri
    - name: enable-log-forward
    - name: scale-resources
    - name: zuul-connections
    - name: zuul-authenticators
    - name: config-update-zuul
    - name: zuul-demo-tenant-workflow
    - name: test-nodepool-providers-secrets
    - name: config-update-nodepool-launcher
    - name: config-update-nodepool-builder
    - name: test-nodepool-launcher-pod
    - name: test-volumestats-sidecar
    - name: expand-volume
    - name: validate-purgelogs
      when: "{{ mode == 'olm' }}"
    - name: zuul-client-api
    - name: zuul-client-from-zuul-pod
    - name: zuul-components
    - name: test-external-ze
    - name: test-log-forwarding
    - name: test-backup-restore
  loop_control:
    loop_var: role
