---
- ansible.builtin.include_role:
    name: setup-variables

- name: Iterate on preparation roles
  ansible.builtin.include_role:
    name: "utils/{{ role }}"
  loop:
    - manage-hosts
    - get-gerrit-admin-user-api-key
    - config-repo-get-or-reset
  loop_control:
    loop_var: role

- name: Iterate on tests
  ansible.builtin.include_role:
    name: "health-check/{{ role }}"
  loop:
    - check-service-uri
    - zuul-connections
    - zuul-authenticators
    - config-update-zuul
    - config-update-nodepool-launcher
    - config-update-nodepool-builder
    - pod-spawning
    - test-volumestats-sidecar
    - test-crd
    - expand-volume
    - validate-purgelogs
    - test-custom-route-certs
    - test-cert-manager-letsencrypt
    - zuul-client-api
    - zuul-components
    - test-monitoring
  loop_control:
    loop_var: role

- name: Check scaling
  ansible.builtin.include_role:
    name: health-check/scale-resources
  loop:
    - up
    - down
  loop_control:
    loop_var: operation
