---
# NOTE: By checking scale-up and scale down before other tests will be running,
# we will make sure, that the services are working correctly.
- name: Check scaling
  ansible.builtin.include_role:
    name: roles/health-check/scale-resources
  loop:
    - up
    - down
  loop_control:
    loop_var: operation

- name: Iterate on tests
  ansible.builtin.include_role:
    name: "roles/{{ role }}"
  loop:
    - utils/manage-hosts
    - utils/get-gerrit-admin-user-api-key
    - health-check/check-service-uri
    - health-check/config-repo-get-or-reset
    - health-check/zuul-connections
  loop_control:
    loop_var: role

- name: Set random value
  ansible.builtin.set_fact:
    random: "{{ lookup('community.general.random_string', special=false, length=8) }}"

- name: Create vars to generate and submit resources addition
  ansible.builtin.set_fact:
    repository_name: "ichiban-config-{{ random }}"
    tenant_name: "ichiban-tenant-{{ random }}"

- ansible.builtin.include_role:
    name: "roles/create-gerrit-repository"

- name: Run tests for config repo
  ansible.builtin.include_role:
    name: "roles/{{ role }}"
  loop:
    - health-check/config-repo-add-zuul-tenant
    - health-check/config-repo-submit-change
  loop_control:
    loop_var: role

- name: Get Zuul projects list
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/api/tenant/{{ tenant_name }}/projects"
    validate_certs: "{{ validate_certs }}"
    method: GET
  register: zuul_tenant_projects
  retries: 10

- name: Ensure project exists in Zuul (fail if not)
  ansible.builtin.fail:
    msg: "Project not found in Zuul"
  when: not (zuul_tenant_projects.json | selectattr('name', 'equalto', repository_name) | length == 1)

- name: Ensure job results exists in Logserver
  ansible.builtin.uri:
    url: "{{ item.log_url }}/job-output.txt.gz"
    validate_certs: "{{ validate_certs }}"
    method: GET
  retries: 10
  loop: "{{ zuul_job_result.json | list }}"

- name: Miscellaneous testing
  ansible.builtin.include_role:
    name: "roles/{{ role }}"
  loop:
    - test-volumestats-sidecar
    - test-crd
    - expand-volume
  loop_control:
    loop_var: role

- name: Ensure data is still present after volume expansion
  ansible.builtin.uri:
    url: "{{ item.log_url }}/job-output.txt.gz"
    validate_certs: "{{ validate_certs }}"
    method: GET
  retries: 10
  loop: "{{ zuul_job_result.json | list }}"

- name: Validate purgelogs
  ansible.builtin.include_role:
    name: "roles/health-check/validate-purgelogs"
