---
- name: Iterate on preparation roles
  ansible.builtin.include_role:
    name: "{{ role.name }}"
  when: role.when | default(true)
  loop:
    - name: setup-variables
    - name: run-operator-standalone
      when: "{{ mode == 'standalone' }}"
    - name: setup-nodepool-ns
    - name: run-operator-standalone
      when: "{{ mode == 'standalone' }}"
    - name: utils/manage-hosts
    - name: utils/get-gerrit-admin-user-api-key
    - name: utils/config-repo-get-or-reset
  loop_control:
    loop_var: role

- name: Iterate on tests
  ansible.builtin.include_role:
    name: "health-check/{{ role.name }}"
  when: role.when | default(true)
  loop:
    - name: initialize-log-forwarding
    - name: check-service-uri
    - name: scale-resources
    - name: zuul-connections
    - name: zuul-authenticators
    - name: config-update-zuul
    - name: test-nodepool-providers-secrets
    - name: config-update-nodepool-launcher
    - name: config-update-nodepool-builder
    - name: pod-spawning
    - name: test-volumestats-sidecar
    - name: expand-volume
    - name: validate-purgelogs
    - name: test-custom-certs
    - name: test-cert-manager-letsencrypt
      when: "{{ mode == 'olm' }}"
    - name: zuul-client-api
    - name: test-monitoring
      when: "{{ test_monitoring == 'true' }}"
    - name: zuul-components
    - name: test-log-forwarding
  loop_control:
    loop_var: role
