---
- name: Iterate on preparation roles
  ansible.builtin.include_role:
    name: "roles/utils/{{ role }}"
  loop:
    - manage-hosts
    - get-gerrit-admin-user-api-key
    - config-repo-get-or-reset
  loop_control:
    loop_var: role

- name: Iterate on tests
  ansible.builtin.include_role:
    name: "roles/health-check/{{ role }}"
  loop:
    - check-service-uri
    - zuul-connections
    - config-update-zuul
    - config-update-nodepool-launcher
    - pod-spawning
    - ensure-job-result-artifacts
    - test-volumestats-sidecar
    - test-crd
    - expand-volume
    - ensure-job-result-artifacts
    - validate-purgelogs
    - replace-route-cert
  loop_control:
    loop_var: role

- name: Check scaling
  ansible.builtin.include_role:
    name: roles/health-check/scale-resources
  loop:
    - up
    - down
  loop_control:
    loop_var: operation
