- name: Download kind
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/download/v0.14.0/kind-linux-amd64
    dest: /bin/kind
    mode: '0755'
    checksum: "sha256:af5e8331f2165feab52ec2ae07c427c7b66f4ad044d09f253004a20252524c8b"
  become: true

- name: Setup kind-config
  copy:
    content: |
      kind: Cluster
      apiVersion:  kind.x-k8s.io/v1alpha4
      nodes:
      - role: control-plane
        kubeadmConfigPatches:  # Enable the creation of ingress controller
        - |
          kind: InitConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              node-labels: "ingress-ready=true"

        extraPortMappings:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
    dest: /etc/kind-config.yaml
  become: true

- name: Install packages
  package:
    name:
      # Podman is presently failing with:
      # ERROR: failed to create cluster: command "podman run --name kind-control-plane..."
      # Command Output: Error: netavark: failed to configure bridge and veth interface: failed while configuring network interface: failed to set ip address to podman1: Permission denied (os error 13)
      # - podman
      - docker
      - kubernetes-client
  become: true

- name: Start docker
  service:
    name: docker
    state: started
  become: true

- name: Create cluster
  command: kind create cluster --config /etc/kind-config.yaml
  become: true

- name: Setup kubeconfig
  shell: |
    mkdir -p {{ ansible_env.HOME }}/.kube
    cp /root/.kube/config {{ ansible_env.HOME }}/.kube/config
    chown -R 1000:1000 {{ ansible_env.HOME }}/.kube
  become: true

- name: Validate cluster
  command: kubectl cluster-info

# - name: Setup ingress controller
#   command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
