---
- name: "Sync sf-operator to {{ microshift_host }}:{{ src_dir }} instance"
  when: remote_os_host
  ansible.builtin.command: >
    rsync
    -e 'ssh -o StrictHostKeyChecking=no'
    -av {{ zuul.project.src_dir }}/
    {{ microshift_host }}:{{ src_dir }}
    --exclude=.git
    --delete
  tags:
    - skip_ansible_lint

- name: "Installing Operator Tools"
  delegate_to: "{{ os_host }}"
  community.general.make:
    target: "{{ inner_item }}"
    chdir: "{{ src_dir }}"
  loop_control:
    loop_var: inner_item
  loop:
    - kustomize
    - controller-gen
    - operator-sdk

- name: Setup a local temporary registry
  delegate_to: "{{ os_host }}"
  block:
    - name: Setup local registry
      ansible.builtin.include_role:
        name: "setup-local-registry"
  when:
    - build_bundle | default(true)

- name: Build and publish operator assets
  delegate_to: "{{ os_host }}"
  block:
    # Image will be available in crio and Microshift will find it
    - name: Build the operator image
      become: true
      community.general.make:
        target: operator-build
        chdir: "{{ src_dir }}"

    - name: Create the operator OLM bundle
      community.general.make:
        target: bundle
        chdir: "{{ src_dir }}"

    - name: Build the operator OLM bundle image
      community.general.make:
        target: bundle-build
        chdir: "{{ src_dir }}"
        params:
          BUNDLE_IMG: "{{ ci_bundle_img }}"

    # operator-sdk run commands requires the bundle image to be available on registry
    - name: Push the OLM bundle image in the local registry
      ansible.builtin.command: podman push --tls-verify=false localhost:5000/sf-operator-bundle:latest
  when:
    - build_bundle | default(true)
