---
- name: Config repo, reset
  ansible.builtin.command: "{{ git_cmd }}"
  args:
    chdir: "{{ config_path }}"
  loop:
    - git fetch --all
    - git checkout master
    - git reset --hard origin/master --
    - git clean -f -d
  loop_control:
    loop_var: git_cmd
  tags:
    - skip_ansible_lint
