---
- name: "Ensure removal of {{ output_dir }}"
  ansible.builtin.file:
    path: "{{ output_dir }}"
    state: absent

- name: "Fetch nodepool-builder /var/lib/nodepool/builds/logs content locally in {{ output_dir }}"
  ansible.builtin.command: |
    kubectl cp nodepool-builder-0:/var/lib/nodepool/builds/logs -c nodepool-builder {{ output_dir }}
  failed_when: false
