---
- name: Dump current secrets from nodepool
  ansible.builtin.command: >
    go run main.go {{ cli_global_flags }} nodepool get providers-secrets --clouds /tmp/clouds.yaml --kube /tmp/kubeconfig.yaml
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: set a fake clouds.yaml configuration
  ansible.builtin.copy:
    src: clouds.yaml
    dest: /tmp/clouds.yaml

- name: Upload clouds secrets to nodepool
  ansible.builtin.command: >
    go run main.go {{ cli_global_flags }} nodepool configure providers-secrets --clouds /tmp/clouds.yaml --kube /tmp/kubeconfig.yaml
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Wait for secrets to be updated
  ansible.builtin.include_role:
    name: "health-check/check-sf-resource-ready"

- name: "Check that clouds.yaml available in nodepool-builder"
  ansible.builtin.shell: |
    kubectl exec nodepool-builder-0 -- bash -c "ls /var/lib/nodepool/.config/openstack/clouds.yaml"
  register: _result
  retries: 60
  delay: 1
  until: _result.rc == 0

- name: "Check that clouds.yaml available in nodepool-launcher containers"
  ansible.builtin.shell: |
    POD=$(kubectl get pods -l=run=nodepool-launcher -o name | tail -n 1)
    kubectl exec $POD -- bash -c "ls /var/lib/nodepool/.config/openstack/clouds.yaml"
  register: _result
  retries: 60
  delay: 1
  until: _result.rc == 0
