---
- name: Setting Dummy Connections
  set_fact:
    dummy_gerritconn:
      - name: dummy-gerrit-conn
        hostname: dummy-gerrit.local
        username: zuul
    dummy_githubconns:
      - name: dummy-github-conn
        appId: githubId
        appKey: githubKey
        apiToken: githubToken
        webHookToken: githubwebtoken

- name: Get current Zuul gerrit connections
  command: kubectl get sf my-sf -o jsonpath='{.spec.zuul.gerritconns}'
  register: gerritconns

- set_fact:
    gerritconns_orig: "{{ gerritconns.stdout | from_json }}"

- name: Add a dummy Zuul Gerrit connection
  ansible.builtin.include_role:
    name: "update-custom-resource"
  vars:
    cr_spec:
      zuul:
        gerritconns: "{{ gerritconns_orig + dummy_gerritconn }}"
        githubconns: "{{ dummy_githubconns }}"

- name: Wait for the new Zuul connection to appear in the Zuul API
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/api/connections"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
  register: this
  until:
    - "'dummy-gerrit-conn' in this.content"
    - "'dummy-github-conn' in this.content"
  retries: "{{ retries }}"
  delay: "{{ delay }}"

- name: Delete the dummy Zuul Gerrit connection
  ansible.builtin.include_role:
    name: "update-custom-resource"
  vars:
    cr_spec:
      zuul:
        gerritconns: "{{ gerritconns_orig }}"
        githubconns: []

- name: Wait for the dummy Zuul connection to be removed from the API
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/api/connections"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
  register: this
  until:
    - "'dummy-gerrit-conn' not in this.content"
    - "'dummy-github-conn' not in this.content"
  retries: "{{ retries }}"
  delay: "{{ delay }}"
