---
- name: Add a dummy Zuul Gerrit connection
  ansible.builtin.include_role:
    name: "roles/update-custom-resource"
  vars:
    cr_spec:
      zuul:
        gerritconns:
          - name: dummy-gerrit-conn
            hostname: dummy-gerrit.local
            username: zuul

- name: Wait for the new Zuul connection to appear in the Zuul API
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/api/connections"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
  register: this
  until: "'dummy-gerrit-conn' in this.content"
  retries: "{{ retries }}"
  delay: "{{ delay }}"

- name: Delete the dummy Zuul Gerrit connection
  ansible.builtin.include_role:
    name: "roles/update-custom-resource"
  vars:
    cr_spec:
      zuul:
        gerritconns: []

- name: Wait for the dummy Zuul connection to be removed from the API
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/api/connections"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
  register: this
  until: "'dummy-gerrit-conn' not in this.content"
  retries: "{{ retries }}"
  delay: "{{ delay }}"
