---
- name: Setting Dummy Connections
  set_fact:
    dummy_gerritconn:
      - name: dummy-gerrit-conn
        hostname: dummy-gerrit.local
        username: zuul
    dummy_githubconns:
      - name: dummy-github-conn
        secrets: githubconnectionsecret
    dummy_gitlabconns:
      - name: dummy-gitlab-conn
        secrets: gitlabconnectionsecret
    dummy_gitconns:
      - name: dummy-git-conn
        baseurl: git://test

- name: Create GitHub Connection Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: githubconnectionsecret
        namespace: sf
      data:
        webhook_token: "{{ '0000000000000000000000000000000000000000' | b64encode }}"
        api_token: "{{ 'ghp_51abcFzcvf3GxOJpPFUKxsT6JIL3Nnbf39E' | b64encode }}"

- name: Create GitLab Connection Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlabconnectionsecret
        namespace: sf
      data:
        api_token: "{{ '0000000000000000000000000000000000000000' | b64encode }}"
        api_token_name: "{{ 'apiTokenName' | b64encode }}"
        webhook_token: "{{ '0000000000000000000000000000000000000000' | b64encode }}"
        sshkey: "{{ '0000000000000000000000000000000000000000' | b64encode }}"

- name: Get current Zuul gerrit connections
  command: |
    {% if mode == 'olm' %}
    kubectl get sf my-sf -o jsonpath='{.spec.zuul.gerritconns}'
    {% else %}
    echo '[{"name": "gerrit", "username": "zuul", "hostname": "gerrit-sshd", "puburl": "https://gerrit.sfop.me"}]'
    {% endif %}
  register: gerritconns

- set_fact:
    gerritconns_orig: "{{ gerritconns.stdout | from_json }}"

- block:
    - name: Add dummy Zuul connections
      ansible.builtin.include_role:
        name: "update-custom-resource"
      vars:
        cr_spec:
          zuul:
            gerritconns: "{{ gerritconns_orig + dummy_gerritconn }}"
            githubconns: "{{ dummy_githubconns }}"
            gitlabconns: "{{ dummy_gitlabconns }}"
            gitconns: "{{ dummy_gitconns }}"

    - name: Wait for the new Zuul connections to appear in the Zuul API
      ansible.builtin.uri:
        url: "https://{{ zuul_host }}/api/connections"
        method: GET
        return_content: true
        validate_certs: "{{ validate_certs }}"
      register: this
      until:
        - "'dummy-gerrit-conn' in this.content"
        - "'dummy-github-conn' in this.content"
        - "'dummy-gitlab-conn' in this.content"
        - "'dummy-git-conn' in this.content"
      retries: "{{ zuul_api_retries }}"
      delay: "{{ zuul_api_delay }}"

    - name: Delete the dummy Zuul connections
      ansible.builtin.include_role:
        name: "update-custom-resource"
      vars:
        cr_spec:
          zuul:
            gerritconns: "{{ gerritconns_orig }}"
            githubconns: []
            gitlabconns: []
            gitconns: []

    - name: Wait for the dummy Zuul connections to be removed from the API
      ansible.builtin.uri:
        url: "https://{{ zuul_host }}/api/connections"
        method: GET
        return_content: true
        validate_certs: "{{ validate_certs }}"
      register: this
      until:
        - "'dummy-gerrit-conn' not in this.content"
        - "'dummy-github-conn' not in this.content"
        - "'dummy-gitlab-conn' not in this.content"
        - "'dummy-git-conn' not in this.content"
      retries: "{{ zuul_api_retries }}"
      delay: "{{ zuul_api_delay }}"

  always:
    - name: Delete GitHub Connection Secret
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Secret
        namespace: sf
        name: githubconnectionsecret

    - name: Delete GitLab Connection Secret
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Secret
        namespace: sf
        name: gitlabconnectionsecret
