---
# './bin/operator-sdk cleanup -n bundle-catalog-ns sf-operator' should do the cleaning here
# However a cert-manager sub is installed into bundle-catalog-ns ns because OLM detected a
# dependency to the cert-manager CRDs, then using "operator-sdk cleanup" remove the cert-manager CRDs
# installed by "make install-cert-manager" into the "operators" ns.
# We might have an inconsistency in our dev workflow if we keep the "go run" dev mode ...
- name: Clean up previous operator installation
  when: remote_os_host
  block:
    - name: Clean the subscription
      ansible.builtin.shell: >
        kubectl -n bundle-catalog-ns get sub --no-headers |
        grep sf-operator |
        cut -d' ' -f1 |
        xargs kubectl -n bundle-catalog-ns delete sub
      ignore_errors: true
      tags:
        - skip_ansible_lint
        - op_delete_sub

    - name: Clean the catalogsource
      ansible.builtin.command: >
        kubectl -n bundle-catalog-ns
        delete catalogsource.operators.coreos.com/sf-operator-catalog
      ignore_errors: true
      tags:
        - skip_ansible_lint
        - op_delete_catsrc

    - name: Clean the csv
      ansible.builtin.shell: >
        kubectl -n bundle-catalog-ns get csv --no-headers |
        grep sf-operator |
        cut -d' ' -f1 |
        xargs kubectl -n bundle-catalog-ns delete csv
      ignore_errors: true
      tags:
        - skip_ansible_lint
        - op_delete_csv

    - name: Remove Software Factory operand(s) in the sf namespace
      ansible.builtin.command: kubectl -n sf delete sf --all
      ignore_errors: true
      tags:
        - skip_ansible_lint
        - sf_delete_instance

    - name: Release PVCs created by the Software Factory operator in the sf namespace
      ansible.builtin.command: kubectl -n sf delete pvc -l app=sf
      ignore_errors: true
      tags:
        - skip_ansible_lint
        - sf_delete_pcvs
