apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zookeeper-client
  labels:
    app.kubernetes.io/name: zookeeper-client-certificate
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zookeeper-client-certificate
spec:
  keyEncoding: pkcs8
  secretName: zookeeper-client-tls
  commonName: client
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: ca-issuer
    kind: Issuer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zuul-scheduler
  labels:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-scheduler
spec:
  replicas: 1
  serviceName: zuul-scheduler
  selector:
    matchLabels:
      app.kubernetes.io/name: zuul
      app.kubernetes.io/part-of: zuul
      app.kubernetes.io/component: zuul-scheduler
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
        app.kubernetes.io/component: zuul-scheduler
    spec:
      containers:
      - name: scheduler
        image: quay.io/software-factory/zuul-scheduler-ubi:5.2.2-3
        args: ["zuul-scheduler", "-f", "-d"]
        env:
          - name: ZUUL_DB_URI
            valueFrom:
              secretKeyRef:
                key: dburi
                name: zuul-db-uri
          - name: ZUUL_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: zuul-keystore-password
                name: zuul-keystore-password
          - name: ZUUL_ZK_HOSTS
            valueFrom:
              secretKeyRef:
                key: zk-hosts
                name: zk-hosts
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
          readOnly: true
        - name: zuul-tenant-yaml
          mountPath: /etc/zuul/tenant
          readOnly: true
        - name: zuul-scheduler
          mountPath: /var/lib/zuul
        - name: zookeeper-client-tls
          mountPath: /tls/client
          readOnly: true
      volumes:
      - name: zuul-config
        secret:
          secretName: zuul-config
      - name: zuul-tenant-yaml
        secret:
          secretName: zuul-tenant-yaml
      - name: zookeeper-client-tls
        secret:
          secretName: zookeeper-client-tls
  volumeClaimTemplates:
  - metadata:
      name: zuul-scheduler
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-web
  labels:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-web
spec:
  type: NodePort
  ports:
  - name: zuul-web
    port: 9000
    protocol: TCP
    targetPort: zuul-web
  selector:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-web
  labels:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: zuul-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zuul
      app.kubernetes.io/part-of: zuul
      app.kubernetes.io/component: zuul-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zuul
        app.kubernetes.io/part-of: zuul
        app.kubernetes.io/component: zuul-web
    spec:
      containers:
      - name: web
        image: quay.io/software-factory/zuul-web-ubi:5.2.2-3
        env:
          - name: ZUUL_DB_URI
            valueFrom:
              secretKeyRef:
                key: dburi
                name: zuul-db-uri
          - name: ZUUL_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: zuul-keystore-password
                name: zuul-keystore-password
          - name: ZUUL_ZK_HOSTS
            valueFrom:
              secretKeyRef:
                key: zk-hosts
                name: zk-hosts
        ports:
        - name: zuul-web
          containerPort: 9000
        volumeMounts:
        - name: zuul-config
          mountPath: /etc/zuul
        - name: zookeeper-client-tls
          mountPath: /tls/client
          readOnly: true
      volumes:
      - name: zuul-config
        secret:
          secretName: zuul-config
      - name: zookeeper-client-tls
        secret:
          secretName: zookeeper-client-tls
