- name: Apply the custom resources
  command: kubectl apply -f playbooks/files/allinone.yaml
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Wait for the custom resources to be ready
  command: kubectl get sf my-sf -o=jsonpath='{.status.ready}'
  register: sf_ready
  until: "'true' in sf_ready.stdout"
  retries: 60
  delay: 10
