---
- name: Apply the custom resources
  ansible.builtin.command: kubectl apply -f playbooks/files/allinone.yaml
  args:
    chdir: "{{ zuul.project.src_dir }}"

- ansible.builtin.include_role:
    name: "roles/health-check/check-sf-resource-ready"
