---
# no_log is set to avoid full content on ansible output
- name: Attempt to access Gerrit
  ansible.builtin.uri:
    url: "https://{{ gerrit_host }}"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
  register: this
  until: "'PolyGerrit' in this.content"
  retries: "{{ retries }}"

- name: Attempt to access Zuul info via API
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/api/info"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
  register: this
  until: fqdn in this.content
  retries: "{{ retries }}"

- name: Attempt to access Zuul pipelines for internal tenant via API
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/api/tenant/internal/pipelines"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
  register: this
  until: "'check' in this.content"
  retries: "{{ retries }}"

- name: Attempt to access Zuul web status page
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/status"
    method: GET
    validate_certs: "{{ validate_certs }}"
    status_code: 200
  retries: "{{ retries }}"

- name: Attempt to access Zuul web internal tenant status page
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/internal/status"
    method: GET
    validate_certs: "{{ validate_certs }}"
    status_code: 200
  retries: "{{ retries }}"

- name: Attempt to access Logserver web
  ansible.builtin.uri:
    url: "https://{{ logserver_host }}/logs/"
    method: GET
    validate_certs: "{{ validate_certs }}"
    status_code: 200
  retries: "{{ retries }}"
