---
# The ingress/route can take some time to set-up and may return 503 thus
# we accept HTTP status code 200 and 503 but success only on 200

- name: Attempt to access Gerrit
  ansible.builtin.uri:
    url: "https://{{ gerrit_host }}"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
    status_code: [200, 503]
  register: this
  until:
    - this.status == 200
    - "'PolyGerrit' in this.content"
  retries: "{{ retries }}"

- name: Attempt to access Zuul info via API
  ansible.builtin.uri:
    url: "https://{{ zuul_endpoint }}/api/info"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
    status_code: [200, 503]
  register: this
  until:
    - this.status == 200
    - "'info' in this.content"
  retries: "{{ zuul_api_retries }}"
  delay: "{{ zuul_api_delay }}"

- name: Attempt to access Zuul pipelines for internal tenant via API
  ansible.builtin.uri:
    url: "https://{{ zuul_endpoint }}/api/tenant/internal/pipelines"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
    status_code: [200, 503]
  register: this
  until:
    - this.status == 200
    - "'check' in this.content"
  retries: "{{ zuul_api_retries }}"
  delay: "{{ zuul_api_delay }}"

- name: Attempt to access Zuul web status page
  ansible.builtin.uri:
    url: "https://{{ zuul_endpoint }}/status"
    method: GET
    validate_certs: "{{ validate_certs }}"
    status_code: [200, 503]
  register: this
  until:
    - this.status == 200
  retries: "{{ zuul_api_retries }}"
  delay: "{{ zuul_api_delay }}"

- name: Attempt to access Zuul web internal tenant status page
  ansible.builtin.uri:
    url: "https://{{ zuul_endpoint }}/internal/status"
    method: GET
    validate_certs: "{{ validate_certs }}"
    status_code: [200, 503]
  register: this
  until:
    - this.status == 200
  retries: "{{ zuul_api_retries }}"
  delay: "{{ zuul_api_delay }}"

- name: Attempt to access Logserver web
  ansible.builtin.uri:
    url: "https://{{ logserver_endpoint }}"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
    status_code: [200, 503]
  register: this
  until:
    - this.status == 200
    - "'Index of /logs' in this.content"
  retries: "{{ retries }}"

- name: Attempt to access Nodepool launcher API
  ansible.builtin.uri:
    url: "https://{{ nodepool_endpoint }}/api/ready"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
    status_code: [200, 503]
  register: this
  until:
    - this.status == 200
    - "'OK' in this.content"
  retries: "{{ retries }}"

- name: Attempt to access Nodepool builder build logs
  ansible.builtin.uri:
    url: "https://{{ nodepool_endpoint }}/builds"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs }}"
    status_code: [200, 503]
  register: this
  until:
    - this.status == 200
    - "'Index of /nodepool/builds' in this.content"
  retries: "{{ retries }}"
