- project:
    vars:
      # NOTE(dpawlik): We don't need to add roles dir, due there is a symlink
      # done in playbooks that is related to roles dir.
      ansible_lint_playbooks_dir: playbooks
      ansible_lint_check_all: false
    check:
      jobs:
        - sf-operator-olm
        - sf-operator-upgrade
        - sf-operator-dev-multinode
        - ansible-lint
    gate:
      jobs:
        - sf-operator-olm
        - sf-operator-upgrade
        - sf-operator-dev-multinode
        - ansible-lint
    post:
      jobs:
        - sf-operator-publish-olm-bundle-image
