- project:
    check:
      jobs:
        - sf-operator-olm
        - sf-operator-upgrade
        - sf-operator-dev-multinode
        - sf-operator-ansible-lint
    gate:
      jobs:
        - sf-operator-olm
        - sf-operator-upgrade
        - sf-operator-dev-multinode
        - sf-operator-ansible-lint
    release:
      jobs:
        - sf-operator-publish-olm-bundle-image
