- project:
    check:
      jobs:
        - sf-operator-functional-allinone-microshift
    gate:
      jobs:
        - sf-operator-functional-allinone-microshift
    periodic:
      jobs:
        - sf-operator-functional-allinone-microshift
