- project:
    check:
      jobs:
        - sf-operator-vuln-check
        - sf-operator-ansible-lint
        - sf-operator-olm-rhel
        - sf-operator-upgrade-rhel
        - sf-operator-standalone-rhel
    gate:
      jobs:
        - sf-operator-vuln-check
        - sf-operator-ansible-lint
        - sf-operator-olm-rhel
        - sf-operator-upgrade-rhel
        - sf-operator-standalone-rhel
    release:
      jobs:
        - sf-operator-publish-olm-bundle-image
    periodic:
      jobs:
        - sf-operator-olm-rhel
        - sf-operator-upgrade-rhel
        - sf-operator-standalone-rhel
