---
apiVersion: v1
kind: Namespace
metadata:
  name: nodepool

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodepool
  namespace: nodepool

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodepool-role
  namespace: nodepool
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
      - persistentvolumeclaims
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodepool
  namespace: nodepool
subjects:
  - kind: ServiceAccount
    name: nodepool
roleRef:
  kind: Role
  name: nodepool-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  namespace: nodepool
  annotations:
    kubernetes.io/service-account.name: nodepool
  name: nodepool-sa-secret
type: kubernetes.io/service-account-token
