---
- name: Ensure ~/zuul-output/logs
  ansible.builtin.file:
    path: ~/zuul-output/logs
    state: directory
  when:
    - glue

# Empty the sf-operator.log output before the run
- name: Ensure ~/zuul-output/logs
  ansible.builtin.file:
    path: ~/zuul-output/logs/sf-operator.log
    state: absent
  when:
    - glue

- name: Run the operator in standalone mode
  ansible.builtin.shell: |
    set -o pipefail
    go run ./main.go --namespace sf dev create standalone-sf --cr {{ cr_path }} 2>&1 | tee -a ~/zuul-output/logs/sf-operator.log
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Copy current spec
  ansible.builtin.shell: "cp {{ cr_path }} /tmp/current_cr.yaml"
  args:
    chdir: "{{ zuul.project.src_dir }}"
  when:
    - glue
