- name: Ensure job results exists in Logserver
  ansible.builtin.include_role:
    name: "health-check/ensure-job-result-artifacts"
  vars:
    log_url: "{{ zuul_config_update_build_log_url }}"

- name: Create a local archive of the logserver content
  ansible.builtin.shell: >
    kubectl exec {{ pod_name }} -c {{ container_name }} -- bash -c "cd /var/www/html/logs/; tar -czf /tmp/logserver.tgz ."

- name: Save logserver content before changing the date
  ansible.builtin.shell: >
    kubectl cp {{ pod_name }}:/tmp/logserver.tgz -c {{ container_name }} /tmp/logserver.tgz

- name: Changing Logs modified time
  ansible.builtin.shell: >
    kubectl exec {{ pod_name }} -c {{ sshd_container_name }}
    -- find /home/data/rsync/ -mindepth 1 -exec touch --date="1970-01-01" {} \;

- name: Change logserver/purgelogs loop delay
  ansible.builtin.include_role:
    name: "update-custom-resource"
  vars:
    cr_spec:
      logserver:
        loopDelay: 5

- name: Ensure logserver/purgelog restarted with correct loopDelay
  command: kubectl get pods {{ pod_name }} -o jsonpath="{.spec.containers[?(@.name=='purgelogs')].command}"
  register: purgelogs_command
  until: purgelogs_command is not failed and "5" in purgelogs_command.stdout
  delay: 5
  retries: 6

- name: Sleep for few seconds to let purgelogs purge old logs
  ansible.builtin.wait_for:
    timeout: 10

- name: Ensure job results do not exist in Logserver after purging
  ansible.builtin.include_role:
    name: "health-check/ensure-job-result-artifacts"
  vars:
    log_url: "{{ zuul_config_update_build_log_url }}"
    status: 404

- name: Upload logserver backup content to pod
  ansible.builtin.shell: >
    kubectl cp /tmp/logserver.tgz {{ pod_name }}:/tmp/ -c {{ container_name }}

- name: Restore logserver content
  ansible.builtin.shell: >
    kubectl exec {{ pod_name }} -c {{ container_name }} --
    bash -c "mkdir -p /tmp/logs && tar -xvf /tmp/logserver.tgz -C /tmp/logs/ && cp -Rf /tmp/logs/* /var/www/html/logs/"

- name: Ensure logserver content restoring worked
  ansible.builtin.include_role:
    name: "health-check/ensure-job-result-artifacts"
  vars:
    log_url: "{{ zuul_config_update_build_log_url }}"
