- hosts: "{{ hostname | default('controller') }}"
  roles:
    - install-golang
  tasks:
    - name: Installing packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - python3-pip
          - python3-setuptools
          - unzip

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - git-review
          - kubernetes
          - oauthlib>=3.2.2
          - websocket-client
