---
- hosts: "{{ hostname | default('controller') }}"
  vars:
    kubectl: "minikube kubectl -- "
    # Kubernetes Version used by Minikube
    # https://kubernetes.io/releases/version-skew-policy/
    kubernetes_version: v1.32
    minikube_package: https://github.com/kubernetes/minikube/releases/download/v1.35.0/minikube-linux-amd64
    kicbase_version: v0.0.46 # keep in sync with the minikube release
    etcd_ramdisk_path: /dev/shm/etcd
    do_create_ramdisk: "{{ create_ramdisk is defined and create_ramdisk == True }}"
    ramdisk_command: |
      {% if do_create_ramdisk %}--mount --mount-string="{{ etcd_ramdisk_path }}:/var/lib/minikube/etcd"
      {% endif %}
  tasks:
    # This task is for slow machine, e.g. in SF CI, it is recommened to setup etcd data in RAM
    - name: Create ramdisk folder
      when: do_create_ramdisk
      become: true
      ansible.builtin.file:
        path: "{{ etcd_ramdisk_path }}"
        state: directory
        mode: 0700
        owner: root
        group: root

    - name: Installing packages
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - podman
          - bind-utils

    - name: Installing Minikube
      become: true
      ansible.builtin.uri:
        url: "{{ minikube_package }}"
        dest: /usr/bin/minikube
        mode: "0755"
        status_code: [200, 304]

    # This try to work-around the minikube start error described below, for which we believe the podman pull is somehow interrupted midway when running in Zuul.
    # By pulling in advance, it seems like we avoid the container storage issue
    - name: Pull the minikube image
      command: "podman pull gcr.io/k8s-minikube/kicbase:{{ kicbase_version }}"
      become: true

    - name: Start minikube
      command: >-
          minikube start
          --kubernetes-version={{ kubernetes_version }}
          --embed-certs
          --container-runtime=cri-o
          --addons ingress,ingress-dns
          --cpus no-limit
          --memory no-limit
          --delete-on-failure=true
          --disable-metrics=true
          {{ ramdisk_command }}

    - name: Install minikube service
      template:
        src: minikube.service.j2
        dest: /etc/systemd/system/minikube.service
      become: true

    - name: Enable minikube service
      ansible.builtin.systemd_service:
        name: minikube
        enabled: true
        daemon_reload: yes
      become: true

    - name: Test minikube
      ansible.builtin.command:
        cmd: "{{ kubectl }} get pod -A"
