---
- hosts: "{{ hostname | default('controller') }}"
  roles:
    - setup-variables
    - setup-env
    - sanity-check
    - setup-namespaces
    - start-gerrit
  tasks:
    - name: CI process(standalone)
      block:
        - community.general.make:
            target: "{{ item }}"
            chdir: "{{ zuul.project.src_dir }}"
          loop:
            - install-cert-manager
            - install-prometheus-operator
        - ansible.builtin.include_role:
            name: start-prometheus
      when: mode == 'standalone'

    - name: CI process(OLM install)
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - microshift-workarounds
        - build-operator-assets
        - clean-installations
        - install-operator
        # we start prometheus after installing the operator, to ensure the prometheus-operator dependency was installed properly.
        - start-prometheus
        - apply-custom-resources
      when: mode == 'olm'

    - name: Run tests
      ansible.builtin.include_role:
        name: run-tests
        apply:
          tags:
            - standalone
      tags:
        - always
