---
- hosts: "{{ hostname | default('all') }}"
  roles:
    - setup-env
    - sanity-check
    - setup-namespaces
    - build-operator-assets
    - clean-installations
    - install-operator
    - apply-custom-resources
  tasks:
    - name: Run tests
      ansible.builtin.include_role:
        name: run-tests
        apply:
          tags:
            - test_only
      tags:
        - always
