---
- hosts: "{{ hostname | default('controller') }}"
  roles:
    - setup-variables
    - setup-env
    - sanity-check
    - setup-namespaces
  tasks:
    - name: >-
        Simulates the "dev" process (start with 'go run' the operator)
        that we describe in the CONTRIBUTING doc
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - run-operator-dev
      vars:
        create_test_bundle_ns: false
      when: mode == 'dev'

    - name: CI process(OLM install)
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - microshift-workarounds
        - start-gerrit
        - build-operator-assets
        - clean-installations
        - install-operator
        # we start prometheus after installing the operator, to ensure the prometheus-operator dependency was installed properly.
        - start-prometheus
      when: mode == 'olm'

    - name: Apply custom resources
      ansible.builtin.include_role:
        name: apply-custom-resources

    - name: Run tests
      ansible.builtin.include_role:
        name: run-tests
        apply:
          tags:
            - test_only
      tags:
        - always
