- hosts: "{{ hostname | default('all') }}"
  roles:
    - setup-env
    - setup-microshift
    - build-operator
    - build-operator-image
    - install-operator
    - apply-custom-resources
  tasks:
    - include_role:
        name: run-tests
        apply:
          tags:
            - test_only
      tags:
        - always
