- hosts: "{{ hostname | default('all') }}"
  roles:
    - install-sf-operator
    - run-sf-operator
  tasks:
    - include_role:
        name: test-sf-operator
        apply:
          tags:
            - test_only
      tags:
        - always
