---
- hosts: "{{ hostname | default('controller') }}"
  vars:
    service_name_custom_ssl: logserver
  roles:
    - setup-variables
    - setup-env
    - sanity-check
    - setup-namespaces
    # NOTE: later that cert would be used by health-check/replace-route-cert role.
    - utils/create-route-ssl-cert
  tasks:
    - name: >-
        Simulates the "dev" process (start with 'go run' the operator)
        that we describe in the CONTRIBUTING doc
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - run-operator-dev
      vars:
        create_test_bundle_ns: false
      when: mode == 'dev'

    - name: CI process(OLM install)
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - start-gerrit
        - build-operator-assets
        - clean-installations
        - install-operator
      when: mode == 'olm'

    - name: Apply custom resources
      ansible.builtin.include_role:
        name: apply-custom-resources

    - name: Run tests
      ansible.builtin.include_role:
        name: run-tests
        apply:
          tags:
            - test_only
      tags:
        - always
