---
- hosts: "{{ hostname | default('controller') }}"
  roles:
    - setup-variables
    - setup-env
    - sanity-check
    - sfconfig-dev-prepare
  tasks:
    - name: CI process(OLM install)
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - build-operator-assets
        - clean-installations
        - install-operator
        - apply-custom-resources
      when: mode == 'olm'

    - name: Run tests
      ansible.builtin.include_role:
        name: run-tests
        apply:
          tags:
            - standalone
      tags:
        - always
