- hosts: all
  tasks:
    - name: Get logs
      command: kubectl get all

    - name: Get events
      shell: |
        kubectl get events > ~/zuul-output/logs/events.txt

    - name: Get ingress logs
      shell: |
        kubectl -n ingress-nginx logs -l app.kubernetes.io/name=ingress-nginx > ~/zuul-output/logs/ingress.txt

    - name: Get nodes information
      shell: |
        kubectl describe nodes > ~/zuul-output/logs/nodes.txt

    - name: Get nodes utilization
      shell: |
        kubectl describe nodes | sed -n '/^Allocated /,/^Events:/ { /^  [^(]/ p; } ; /^Name: / p' > ~/zuul-output/logs/nodes-utilization.txt

    - name: Describe resources
      shell: |
        for item in $(kubectl get {{ item }} -o name); do
          mkdir -p ~/zuul-output/logs/$(dirname $item)
          kubectl describe $item > ~/zuul-output/logs/${item}.txt
        done
      ignore_errors: yes
      loop:
        - pods
        - deployments
        - statefulsets
        - services
        - secrets
        - configmaps

    - name: Collect logs
      shell: |
        for pod in $(kubectl get pods -o name); do
          mkdir -p ~/zuul-output/logs/$(dirname $pod)
          kubectl logs $pod > ~/zuul-output/logs/${pod}-logs.txt
        done
