- hosts: "{{ hostname | default('controller') }}"
  tasks:
      # Fetch zuul jobs artifacts stored in the logserver during the sf-operator functional test
      - include_role:
            name: post/get-logserver-content

      # Fetch nodepool-builder build image logs
      - include_role:
            name: post/get-nodepool-builds-logs

      # Fetch k8s cluster wide resources
      - include_role:
            name: post/get-k8s-cluster-resources

      # Fetch k8s resources for the sf namespace
      - include_role:
            name: post/get-k8s-resources
        vars:
            namespace: sf

      # Fetch k8s resources for the sf-operator namespace
      - include_role:
            name: post/get-k8s-resources
        vars:
            namespace: operators

      # Fetch system-config repo
      - include_role:
            name: post/get-system-config

      # Fetch repos stored on code review service
      - include_role:
            name: post/get-repos

      - include_role:
            name: post/get-system-logs

      - include_role:
            name: post/get-loki-logs