- hosts: "{{ hostname | default('all') }}"
  tasks:
    # Fetch zuul jobs artifacts stored in the logserver during the sf-operator functional test
    - include_role:
        name: roles/post/get-logserver-content

    # Fetch k8s cluster wide resources
    - include_role:
        name: roles/post/get-k8s-cluster-resources

    # Fetch k8s resources for the sf namespace
    - include_role:
        name: roles/post/get-k8s-resources
      vars:
        namespace: sf

    # Fetch k8s resources for the sf-operator namespace
    - include_role:
        name: roles/post/get-k8s-resources
      vars:
        namespace: bundle-catalog-ns

    # Fetch system-config repo
    - include_role:
        name: roles/post/get-system-config
