---
- hosts: "{{ hostname | default('controller') }}"
  environment:
    OPENSHIFT_USER: false
  roles:
    - setup-variables
    - setup-nodepool-ns
    - utils/get-gerrit-admin-user-api-key
    - utils/config-repo-reset

    # Apply the sf.yaml resources with the config repo on gerrit
    - run-operator-standalone

    # Validate services are working
    - health-check/check-service-uri
    - health-check/check-zuul-weeder
    # FIXME: add more health-check
