---
- hosts: "{{ hostname | default('controller') }}"
  environment:
    OPENSHIFT_USER: false
  roles:
    - setup-variables
    - setup-nodepool-ns
    - utils/get-gerrit-admin-user-api-key
    - utils/config-repo-reset
    # - utils/setup-log-forwarding-stack

    # - health-check/check-service-uri
    - health-check/check-zuul-weeder
    # FIXME: add more health-check
