---
- hosts: "{{ hostname | default('controller') }}"
  tasks:
    - name: Install golang
      ansible.builtin.include_role:
        name: install-golang

    - name: Installing golang vulnerability tool
      ansible.builtin.command:
        cmd: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Running golang vulnerability test
      ansible.builtin.shell:
        cmd: ~/go/bin/govulncheck -show verbose ./...
        chdir: "{{ zuul.project.src_dir }}"
