---
- hosts: "{{ hostname | default('all') }}"
  tasks:
    - name: Install packages needed by sfconfig for go-ansible (ansible and collections)
      block:
        - name: Install epel
          package:
            name: epel-release

        # collections are available on ansible from epel
        - name: Install ansible and collection
          package:
            name:
              - ansible-core
              - ansible
      become: yes

    - name: Run CI jobs using sfconfig
      command: ./tools/sfconfig runTests --zuul -e 'mode={{ mode | default("ci")}}'
      args:
        chdir: "{{ zuul.project.src_dir }}"
