---
- hosts: all
  vars:
    use_workaround: true
  pre_tasks:
    - name: Start CRC
      shell: |
        /usr/local/bin/crc start --memory 14000 --disk-size 80 --cpus 6

  roles:
    - install-sf-operator
    - run-sf-operator
