---
- hosts: "{{ hostname | default('controller') }}"
  roles:
    - setup-variables
    - setup-env
    - sanity-check
    - setup-namespaces
    - microshift-workarounds
    - start-gerrit
    - start-prometheus
    - role: build-operator-assets
      vars:
        build_bundle: false
    - clean-installations
    - role: install-operator
      vars:
        ci_bundle_img: quay.io/software-factory/sf-operator-bundle:latest
    - apply-custom-resources
    - role: build-operator-assets
      vars:
        build_bundle: true
        ci_bundle_img: localhost:5000/sf-operator-bundle:latest
    - upgrade-operator
  tasks:
    - name: Run tests
      ansible.builtin.include_role:
        name: run-tests
        apply:
          tags:
            - test_only
      tags:
        - always
