---
- hosts: "{{ hostname | default('controller') }}"
  environment:
    OPENSHIFT_USER: "true"
  roles:
    - setup-variables
    - setup-env
    - sanity-check
    - sfconfig-dev-prepare
  tasks:
    - name: Get iplb ip address
      ansible.builtin.command: /usr/local/bin/recognize-iplb-ip-address.sh
      register: _iplb_ip

    - name: Set fact with iplb ip address
      ansible.builtin.set_fact:
        iplb_ip_address: "{{ _iplb_ip.stdout }}"

    - name: Set hostAliases - edit playbooks/files/ yaml files
      ansible.builtin.include_role:
        name: create-hostaliases-cr
      loop:
        - "{{ '~/' + zuul.project.src_dir + '/playbooks' | realpath | default(playbook_dir) }}/files/ext-ze.yaml"
        - "{{ '~/' + zuul.project.src_dir + '/playbooks' | realpath | default(playbook_dir) }}/files/sf.yaml"
        - "{{ '~/' + zuul.project.src_dir + '/playbooks' | realpath | default(playbook_dir) }}/files/sf-operator-cli.yaml"
        - "{{ '~/' + zuul.project.src_dir + '/playbooks' | realpath | default(playbook_dir) }}/files/sf-minimal.yaml"
      loop_control:
        loop_var: yaml_file

    - name: Build operator assets
      ansible.builtin.include_role:
        name: build-operator-assets
      vars:
        build_bundle: false

    - name: Clean installation cli
      ansible.builtin.include_role:
        name: clean-installations-cli

    - name: Install operator
      ansible.builtin.include_role:
        name: install-operator
      vars:
        ci_bundle_img: quay.io/software-factory/sf-operator-bundle:latest

    - name: Add back the config base-url for the previous version. Remove this after v56 is released
      command: |
        sed -e 's|name: config|name: config\n    base-url: "http://gerrit-httpd/"|' -i "playbooks/files/sf.yaml"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Apply custom resources
      ansible.builtin.include_role:
        name: apply-custom-resources

    - name: Remove the config base-url from the previous version. Remove this after v56 is released
      command: |
        sed -e 's|.*base-url: "http://gerrit-httpd/".*||' -i "playbooks/files/sf.yaml"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Build operator assets
      ansible.builtin.include_role:
        name: build-operator-assets
      vars:
        build_bundle: true
        ci_bundle_img: localhost:5000/sf-operator-bundle:latest

    - name: Upgrade operator and run tests
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - upgrade-operator
        - run-tests
