---
- hosts: "{{ hostname | default('controller') }}"
  roles:
    - setup-variables
    - setup-env
    - sanity-check
    - sfconfig-dev-prepare
    - setup-log-forwarding
    - role: build-operator-assets
      vars:
        build_bundle: false
    - clean-installations-cli
    - role: install-operator
      vars:
        ci_bundle_img: quay.io/software-factory/sf-operator-bundle:latest
    - apply-custom-resources
    - role: build-operator-assets
      vars:
        build_bundle: true
        ci_bundle_img: localhost:5000/sf-operator-bundle:latest
    - upgrade-operator
    - run-tests
