---
- name: Clean up previous operator installation
  when: remote_os_host
  ansible.builtin.shell: >
    go run main.go {{ cli_global_flags }} dev wipe sf --rm-data --rm-operator
  args:
    chdir: "{{ zuul.project.src_dir | default(src_dir) }}"
