---
- name: Create test resource commit
  include_tasks: create-test-resource.yaml

- name: Verify Zuul Console output
  include_tasks: ensure-zuul-console-success.yaml

- name: Ensure a success config-update
  include_tasks: ensure-config-update-success.yaml
