---
- name: Submit change
  ansible.builtin.include_tasks: submit-change.yaml

- name: Verify Zuul Console output
  ansible.builtin.include_tasks: ensure-zuul-console-success.yaml

- name: Ensure a success config-update
  ansible.builtin.include_tasks: ensure-config-update-success.yaml
