- name: Submit change
  command: git review
  args:
    chdir: "{{ config_path}}"

- name: Get Change-id
  shell: git log -n 1 | awk '/Change-Id/ {print $2}'
  args:
    chdir: "{{ config_path}}"
  register: _change_id

# documentation: https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#set-review
- name: Set Code-Review and Workflow label using gerrit API
  uri:
    url: "https://{{ gerrit_host}}/a/changes/{{ _change_id.stdout }}/revisions/current/review"
    user: admin
    password: "{{ gerrit_admin_api_key }}"
    body_format: json
    body: >-
      {"labels": {
        "Code-Review": +2,
        "Workflow": +1
        }
      }
    validate_certs: "{{ validate_certs }}"
    method: POST

- name: Get zuul build result
  include_tasks: get_zuul_web_result.yaml
