---
- name: Ensure job console (job-output.txt.gz) exists in Logserver
  ansible.builtin.uri:
    url: "{{ log_url }}/job-output.txt.gz"
    validate_certs: "{{ validate_certs }}"
    method: GET
    status_code:
      - 200
      - 404
  register: this
  until:
    - this.status == status
  retries: "{{ retries }}"
  delay: "{{ delay }}"
