- name: Look for executor ssh key
  set_fact:
    executor_key: "{{ lookup('k8s', api_version='v1', kind='Secret', namespace=namespace, resource_name=zuul_name + '-executor-ssh-key') }}"

- name: Generate executor ssh key
  when: executor_key.data is not defined
  block:
    - name: Generate key
      command: ssh-keygen -f "{{ zuul_name }}-id_rsa" -N '' -m PEM
      args:
        creates: "{{ zuul_name }}-id_rsa"

    - name: Save executor key
      k8s:
        state: "{{ state }}"
        namespace: "{{ namespace }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ zuul_name }}-executor-ssh-key"
          stringData:
            id_rsa: "{{ lookup('file', zuul_name + '-id_rsa') }}"
            id_rsa.pub: "{{ lookup('file', zuul_name + '-id_rsa.pub') }}"
