---
- name: Set random value
  ansible.builtin.set_fact:
    random: "{{ lookup('community.general.random_string', special=false, length=8) }}"

- name: Create vars to generate and submit resources addition
  ansible.builtin.set_fact:
    repository_name: "ichiban-config-{{ random }}"
    tenant_name: "ichiban-tenant-{{ random }}"

- ansible.builtin.include_role:
    name: "roles/create-gerrit-repository"

- name: Set Zuul tenant config
  ansible.builtin.blockinfile:
    content: |
      - tenant:
          name: {{ tenant_name }}
          source:
            gerrit:
              config-projects:
                - {{ repository_name }}
    path: "{{ config_path }}/zuul/main.yaml"
    create: true

- name: Commit file in the config repo
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ config_path }}"
  loop:
    - "git add {{ config_path }}/zuul/main.yaml"
    - "git commit -m 'Add {{ config_path }}/zuul/main.yaml'"

- ansible.builtin.include_role:
    name: "roles/health-check/config-repo-submit-change"

- name: Get Zuul projects list
  ansible.builtin.uri:
    url: "https://{{ zuul_host }}/api/tenant/{{ tenant_name }}/projects"
    validate_certs: "{{ validate_certs }}"
    method: GET
  register: zuul_tenant_projects
  retries: 10

- name: Ensure project exists in Zuul (fail if not)
  ansible.builtin.fail:
    msg: "Project not found in Zuul"
  when: not (zuul_tenant_projects.json | selectattr('name', 'equalto', repository_name) | length == 1)
