---
# Where the operator will be installed via the OLM bundle
- name: Create the bundle-catalog-ns namespace
  shell: |
    kubectl create namespace bundle-catalog-ns
    oc adm policy add-scc-to-user privileged system:serviceaccount:bundle-catalog-ns:default
  when: create_test_bundle_ns

# Where sf instance will be reclaimed
- name: Create namespace
  shell: |
    kubectl create namespace {{ namespace }}
    kubectl config set-context {{ context }} --namespace={{ namespace }}
    kubectl label --overwrite ns {{ namespace }} pod-security.kubernetes.io/enforce=privileged
    kubectl label --overwrite ns {{ namespace }} pod-security.kubernetes.io/enforce-version=v{{ k8s_version }}
    oc adm policy add-scc-to-user privileged -z default
