---
# Where the operator will be installed via the OLM bundle
- name: Create the {{ bundlenamespace }} namespace
  shell: |
    kubectl create namespace {{ bundlenamespace }}
    oc adm policy add-scc-to-user privileged system:serviceaccount:{{ bundlenamespace }}:default
  when: create_test_bundle_ns
  tags:
    - operator_bundle_namespace

# Where sf instance will be reclaimed
- name: Create namespace
  shell: |
    kubectl create namespace {{ namespace }}
    kubectl config set-context {{ context }} --namespace={{ namespace }}
    kubectl label --overwrite ns {{ namespace }} pod-security.kubernetes.io/enforce=privileged
    kubectl label --overwrite ns {{ namespace }} pod-security.kubernetes.io/enforce-version=v{{ k8s_version }}
    oc adm policy add-scc-to-user privileged -z default
  tags:
    - operator_sf_namespace

- name: Setup nodepool namespace
  command: "tools/sfconfig create-namespace-for-nodepool"
  args:
    chdir: "{{ zuul.project.src_dir }}"
